/**
 * OMP config schema 描述英译中映射。
 *
 * 键是 `omp config list --json` 返回的英文 description，值是中文翻译。
 * 渲染时 locale 为 zh-CN 且命中映射则显示中文，否则回退英文原文
 * （schema 会增长，回退保证新字段不空白）。
 *
 * 由 scripts/gen-native-settings-descriptions.mjs --check 校验同步。
 */

const MAP: Record<string, string> = {
  "Action when pressing Escape twice with empty editor": "空编辑器中连续按两次 Escape 时执行的操作",
  "Allow the eval tool to dispatch Julia cells to the persistent Julia kernel": "允许 eval 工具将 Julia 单元发送到持久化 Julia 内核",
  "Allow the eval tool to dispatch Ruby cells to the persistent Ruby kernel": "允许 eval 工具将 Ruby 单元发送到持久化 Ruby 内核",
  "Optional path to an exact Julia executable. When set, automatic Julia runtime discovery is skipped.": "可选的 Julia 可执行文件精确路径。设置后将跳过 Julia 运行时的自动发现。",
  "Prevent macOS sleep during active sessions. Each level is cumulative — it adds the flags of all lower levels.": "活动会话期间阻止 macOS 休眠。每个等级会累加，并包含所有更低等级的标志。",
  "ONNX execution provider for local tiny models (titles + memory). Default uses CPU-only inference. The PI_TINY_DEVICE env var overrides this.": "本地 tiny 模型（标题和记忆）的 ONNX 执行提供程序。默认仅使用 CPU 推理；PI_TINY_DEVICE 环境变量可覆盖此设置。",
  "ONNX quantization/precision for local tiny models. Default uses each model's shipped dtype (q4); lower precision is faster, higher is more faithful. The PI_TINY_DTYPE env var overrides this.": "本地 tiny 模型的 ONNX 量化/精度。默认使用模型随附的数据类型（q4）；低精度更快，高精度更忠实；PI_TINY_DTYPE 环境变量可覆盖此设置。",
  "Optional path to an exact Ruby executable. When set, automatic Ruby runtime discovery is skipped.": "可选的 Ruby 可执行文件精确路径。设置后将跳过 Ruby 运行时的自动发现。",
  "Isolation backend for subagents. \"auto\" lets the native PAL pick the best available backend (CoW-aware filesystems, then overlayfs/ProjFS, then a git worktree / recursive-copy fallback).": "子智能体的隔离后端。\"auto\" 会让原生 PAL 选择最佳可用后端（优先支持 CoW 的文件系统，其次是 overlayfs/ProjFS，最后回退到 git worktree 或递归复制）。",
  "Automatically resume the most recent session in the current directory": "在当前目录自动恢复最近的会话",
  "Prevent the system sleeping during active sessions. Each level is cumulative — it adds the flags of all lower levels.": "在活动会话期间阻止系统休眠。每级是累加的——会包含所有低级别的标志。",
  "Pair a second model (assigned to the 'advisor' role) that passively reviews each turn and injects notes.": "配对第二个模型（分配为「顾问」角色），被动审阅每一轮并注入备注。",
  "Start on the active model, then switch to a fast/cheap model (default the 'smol' role) at the first edit/write after the plan nudge's todo list exists — the strong model plans, commits the todos, and starts the implementation before handing off. Overridable per session with --prewalk / --no-prewalk.": "从当前模型启动，待计划提示的待办清单出现后，在首次编辑/写入时切换至快速/廉价模型（默认「smol」角色）——强模型负责规划、提交待办并开始实现，然后交出控制权。每个会话可用 --prewalk / --no-prewalk 覆盖。",
  "Pause the main agent for up to 30 seconds if the advisor falls behind by this many turns. Off disables catch-up delays.": "若顾问落后这么多轮，主智能体最多暂停 30 秒。关闭则禁用追赶延迟。",
  "After an advisor concern or blocker interrupts, route further concerns/blockers non-interruptingly for this many primary turns.": "在顾问关注点或阻断触发中断后，后续的关注点/阻断将在这么多主轮次内以非中断方式路由。",
  "Show git branch, status, and PR information in the TUI and watch repository metadata.": "在 TUI 中显示 git 分支、状态和 PR 信息，并监听仓库元数据。",
  "Maximum concurrent LLM requests per provider id (for example \"openai\" or \"anthropic\"), shared across local OMP processes with this config root. Omitted providers are unlimited.": "每个提供商 ID（如「openai」或「anthropic」）的最大并发 LLM 请求数，在共享此配置根目录的本地 OMP 进程间共用。省略的提供商不限制。",
  "Route Codex code_mode_only models (GPT-5.6) through eval. The direct tools are eval, ask, todo, yield, think, checkpoint, and rewind. Use eval cells for other session tools. Mirrors codex-rs Code Mode. 'auto' follows the model catalog flag.": "将 Codex code_mode_only 模型（GPT-5.6）路由到 eval。直接工具有 eval、ask、todo、yield、think、checkpoint 和 rewind。其他会话工具使用 eval 单元。镜像 codex-rs Code Mode。「auto」遵循模型目录标志。",
  "Extra direct tools for Codex Code Mode. The standard direct tools are eval, ask, todo, yield, think, checkpoint, and rewind.": "Codex Code Mode 的额外直接工具。标准直接工具有 eval、ask、todo、yield、think、checkpoint 和 rewind。",
  "Where model selector role assignments are saved": "模型选择器角色分配保存位置",
  "Theme used when the terminal has a dark background": "终端深色背景时使用的主题",
  "Theme used when the terminal has a light background": "终端浅色背景时使用的主题",
  "Glyph set for icons and symbols (Unicode, Nerd Font, or ASCII)": "图标和符号的字形集（Unicode、Nerd Font 或 ASCII）",
  "Use blue instead of green for diff additions": "diff 新增行使用蓝色而非绿色",
  "Visual layout of the input editor and status line": "输入编辑器和状态行的视觉布局",
  "Pre-built status line configurations": "预置状态行配置",
  "Style of separators between segments": "段间分隔符样式",
  "How the line between the left and right segments reflects context usage (box composer only)": "左右段之间的连线如何反映上下文使用量（仅 box 编辑器）",
  "Use the session name color for the editor border and status line gap": "编辑器边框和状态行间隙使用会话名称颜色",
  "Use the terminal's default background for the status line instead of the theme's `statusLineBg`. Powerline end caps are dropped because they need a contrasting fill to bridge into the surrounding terminal.": "状态行使用终端默认背景而非主题的 `statusLineBg`。Powerline 端帽会被舍弃，因为它们需要对比色填充才能过渡到周围终端。",
  "Show the thinking level as a single icon on the model name instead of a separate ` · <level>` suffix.": "在模型名称上用一个图标显示思考等级，而非单独的 ` · <level>` 后缀。",
  "Tool output above this size is saved as an artifact; tail is kept inline": "超过此大小的输出保存为构件；尾部保留在行内",
  "Amount of tail content kept inline when output spills to artifact": "输出溢出到构件时保留在行内的尾部内容量",
  "Amount of head content kept inline alongside the tail when output spills to artifact (middle elision). 0 disables — keep tail only.": "输出溢出到构件时与尾部一起保留在行内的头部内容量（中间省略）。0 表示禁用——仅保留尾部。",
  "Per-line byte cap for streaming tool outputs (bash, python, js eval) and `read`. Lines wider than this are ellipsis-truncated; remaining bytes up to the next newline are dropped. 0 disables.": "流式工具输出（bash、python、js eval）和 `read` 的每行字节上限。超宽行会被省略号截断；直到下一换行符前的剩余字节将被丢弃。0 表示禁用。",
  "Maximum lines of tail content kept inline when output spills to artifact": "输出溢出到构件时保留在行内的最大尾部行数",
  "Display hook status messages below the status line": "在状态行下方显示钩子状态消息",
  "Render images inline in the terminal": "在终端内联渲染图片",
  "Resize large images to 2000x2000 max for better model compatibility": "将大图缩放到最大 2000x2000 以提升模型兼容性",
  "Prevent images from being sent to LLM providers": "阻止图片被发送给 LLM 提供商",
  "When an image is attached to a model without vision support, save it under local:// and inject a description from a vision-capable model instead of dropping it": "当图片附加到不支持视觉的模型时，保存到 local:// 并注入来自视觉模型的描述，而非丢弃",
  "Publish outgoing images through the configured backend chain and send URL-fetching providers short URLs instead of inline base64. Falls back to inline automatically when every backend or a provider fetch fails": "通过配置的后端链发布外发图片，向 URL 获取型提供商发送短 URL 而非内联 base64。当所有后端或提供商获取失败时自动回退到内联。",
  "Ordered destinations tried when publishing images for provider access": "发布图片供提供商访问时按顺序尝试的目标",
  "Argv template for the command backend; {file} is the image path, {mime}/{ext} optional. The last URL printed on stdout is used (e.g. pasta -b -f {file})": "命令后端的参数模板；{file} 是图片路径，{mime}/{ext} 可选。使用 stdout 上打印的最后一个 URL（如 pasta -b -f {file}）",
  "Externally reachable base URL fronting the blob server (required for ssh, optional for direct)": "前置 blob 服务器的可外部访问基础 URL（ssh 必需，直连可选）",
  "Serving window for locally hosted image URLs, measured from the last time a conversation sent them; resuming a conversation re-arms the window at the same link. 0 keeps links alive while the broker runs": "本地托管图片 URL 的服务窗口，自上次对话发送时起测量；恢复会话会在同一链接重新激活窗口。0 表示在 broker 运行期间保持链接有效。",
  "Host the blob server binds to; loopback for tunnels, 0.0.0.0 for direct serving": "blob 服务器绑定的主机；隧道用回环地址，直连用 0.0.0.0",
  "user@host destination for the ssh reverse forward": "ssh 反向转发的 user@host 目标",
  "Remote listen port of the ssh reverse forward that your web server proxies to": "ssh 反向转发的远程监听端口，你的 Web 服务器代理到该端口",
  "How a settled terminal resize refreshes transcript rows retained in terminal scrollback": "终端大小调整后如何刷新保留在终端回滚缓冲中的记录行",
  "Emit OSC 9;4 indeterminate progress while the agent or context maintenance is running": "在智能体或上下文维护运行时发出 OSC 9;4 不确定进度信号",
  "Render Markdown H1 headings at 2x scale using Kitty's OSC 66 text-sizing protocol. Only takes effect on Kitty terminals; ignored everywhere else. Off by default.": "使用 Kitty 的 OSC 66 文本缩放协议以 2 倍大小渲染 Markdown H1 标题。仅在 Kitty 终端生效；其他终端忽略。默认关闭。",
  "Render Mermaid fenced code blocks as ASCII diagrams": "将 Mermaid 围栏代码块渲染为 ASCII 图表",
  "Invite the agent to react to your message with an emoji badge on its bubble": "邀请智能体用气泡上的 emoji 徽章回应你的消息",
  "Celebrate unscheduled Codex weekly usage resets and newly banked saved resets with a top-third fireworks overlay that remains until Escape": "用停留在顶部三分之一的烟花覆盖层庆祝未到期的 Codex 每周用量重置和新存入的已保存重置，直到按 Escape 消失",
  "Show the agent run state in the terminal title's separator — an animated spinner while working (a static ':' on Windows), '>' when it's your turn, '!' when the agent is waiting on you": "在终端标题分隔符中显示智能体运行状态——工作时显示动画旋转器（Windows 上为静态「:」），轮到你时显示「>」，智能体等你时显示「!」",
  "Wrap paths and URLs in OSC 8 hyperlinks for terminal-native click-to-open (auto: detect support; off: never; always: unconditional)": "用 OSC 8 超链接包裹路径和 URL，实现终端原生点击打开（auto：检测支持；off：从不；always：无条件）",
  "Remove the 1-character horizontal padding from the left and right of the terminal output": "移除终端输出左右两侧的 1 字符水平内边距",
  "Animation style for working/loading messages": "工作/加载消息的动画样式",
  "Reveal assistant text and streamed tool input smoothly while chunks arrive": "在数据块到达时平滑显示助手文本和流式工具输入",
  "Hide model-initiated tool calls and results from the transcript": "在记录中隐藏模型发起的工具调用和结果",
  "Show per-turn token usage on assistant messages": "在助手消息上显示每轮 token 用量",
  "Show the total prompt-to-yield time (including tool calls) on assistant message usage rows": "在助手消息用量行上显示从提示到产出的总时间（含工具调用）",
  "Show a divider after an assistant turn whose request lost (missed) the prompt cache": "在请求未命中提示缓存的助手轮次后显示分隔线",
  "Collapse pre-compaction history behind the summary divider on the live transcript; disable to keep the full transcript inline with dividers at each compaction point": "在实时记录中将压缩前历史折叠到摘要分隔线后；禁用可保留完整记录并在每个压缩点显示分隔线",
  "Show terminal cursor for IME support": "显示终端光标以支持 IME 输入法",
  "Move the prompt's bottom border to a separate row so macOS IME preedit cannot displace it": "将提示框底部边框移到独立行，避免 macOS IME 预编辑将其挤走",
  "Reasoning depth for thinking-capable models": "支持思考的模型的推理深度",
  "Hide thinking blocks in assistant responses": "在助手回复中隐藏思考块",
  "Omit code blocks from thinking summaries and replace them with an ellipsis": "在思考摘要中省略代码块，用省略号替代",
  "Instruct upstream providers to completely omit thinking summaries from responses (where supported)": "指示上游提供商在回复中完全省略思考摘要（在支持的情况下）",
  "Private scratchpad; not shown to user. Disables supported GPT, Claude, and Gemini reasoning": "私人草稿区；不对用户显示。禁用受支持的 GPT、Claude 和 Gemini 推理",
  "Enable automatic stream loop detection for model reasoning and prose": "启用模型和散文的自动流式循环检测",
  "Apply loop guard to assistant prose messages in addition to thinking logs": "除思考日志外，还对助手散文消息应用循环守护",
  "When a Gemini reasoning stream emits many consecutive planning headers without calling a tool, interrupt it and inject a reminder to issue a tool call (requires Loop Guard)": "当 Gemini 推理流连续发出多个规划标题却未调用工具时，中断并注入提醒要求发出工具调用（需要循环守护）",
  "Detect consecutive identical tool calls across turns and inject a corrective steer": "检测跨轮次的连续相同工具调用并注入纠正引导",
  "Consecutive identical tool calls required before the corrective steer is injected": "注入纠正引导前所需的连续相同工具调用次数",
  "Tool names that may repeat consecutively without triggering the cross-turn loop guard": "可连续重复而不触发跨轮循环守护的工具名称",
  "Render full tool descriptors in the system prompt and strip top-level/nested descriptions from provider tool schemas so descriptor text is sent once. Auto enables this for Gemini models and disables it otherwise": "在系统提示中渲染完整工具描述符，并从提供商工具模式中剥离顶层/嵌套描述，使描述文本仅发送一次。auto 对 Gemini 模型启用，其他禁用。",
  "Surface the active model identifier in the system prompt so the agent knows which model it is": "在系统提示中暴露当前模型标识符，让智能体知道自己是哪个模型",
  "Render the workspace directory tree in the system prompt. WARNING: This can bust prompt caching across sessions when files are modified.": "在系统提示中渲染工作区目录树。警告：文件修改时会破坏跨会话的提示缓存。",
  "List available skills in the system prompt; disable to save context and toggle per-session with /skillful": "在系统提示中列出可用技能；禁用可节省上下文，每个会话可用 /skillful 切换",
  "Extra workspace directories added to every session as additional roots (multi-root workspace). Managed live via /add-dir and /remove-dir. Paths resolve relative to cwd; absolute paths recommended. The agent is told these roots exist and can read/grep/glob them.": "添加到每个会话的额外工作区目录作为附加根（多根工作区）。通过 /add-dir 和 /remove-dir 实时管理。路径相对于 cwd 解析；建议使用绝对路径。智能体会被告知这些根存在并可读取/grep/glob。",
  "Communication style rendered into the system prompt's personality block": "渲染到系统提示人格块中的沟通风格",
  "Sampling temperature (0 = deterministic, 1 = creative, -1 = provider default)": "采样温度（0 = 确定性，1 = 创意，-1 = 提供商默认）",
  "Nucleus sampling cutoff (0-1, -1 = provider default)": "核采样截断（0-1，-1 = 提供商默认）",
  "Sample from top-K tokens (-1 = provider default)": "从 top-K token 中采样（-1 = 提供商默认）",
  "Minimum probability threshold (0-1, -1 = provider default)": "最小概率阈值（0-1，-1 = 提供商默认）",
  "Penalty for introducing already-present tokens (-1 = provider default)": "引入已存在 token 的惩罚（-1 = 提供商默认）",
  "Penalty for repeated tokens (-1 = provider default)": "重复 token 的惩罚（-1 = 提供商默认）",
  "OpenAI Responses and Codex response verbosity (low, medium, or high)": "OpenAI Responses 和 Codex 回复详细程度（低、中、高）",
  "Processing tier for OpenAI / OpenAI-Codex requests, and OpenAI-family models routed via OpenRouter (none = omit). Sent as `service_tier`.": "OpenAI / OpenAI-Codex 请求以及通过 OpenRouter 路由的 OpenAI 系列模型的处理层级（none = 省略）。作为 `service_tier` 发送。",
  "Processing tier for Claude requests. `priority` realizes fast mode (`speed: \"fast\"`) on supported direct Anthropic models; ignored on Bedrock/Vertex Claude and via OpenRouter.": "Claude 请求的处理层级。`priority` 在受支持的直连 Anthropic 模型上实现快速模式（`speed: \"fast\"`）；在 Bedrock/Vertex Claude 和通过 OpenRouter 时忽略。",
  "Processing tier for Gemini (Google AI Studio + Vertex) requests, and Google-family models routed via OpenRouter (none = omit). Sent as the top-level `serviceTier` field.": "Gemini（Google AI Studio + Vertex）请求以及通过 OpenRouter 路由的 Google 系列模型的处理层级（none = 省略）。作为顶层 `serviceTier` 字段发送。",
  "Service Tier for spawned task/eval subagents. Inherit = match the main agent's live per-family tiers (tracks /fast); pick a value to apply it to whichever family the subagent's model belongs to.": "派生的任务/评估子智能体的服务层级。Inherit = 匹配主智能体当前按家族层级的设置（跟踪 /fast）；选择值则应用于子智能体模型所属的家族。",
  "Service Tier for the advisor model. None = standard processing; Inherit = match the main agent's live per-family tiers; pick a value to apply it to the advisor model's family.": "顾问模型的服务层级。None = 标准处理；Inherit = 匹配主智能体当前按家族层级的设置；选择值则应用于顾问模型的家族。",
  "Maximum retry attempts on API errors": "API 错误的最大重试次数",
  "Maximum wait between retries, in ms. When the provider asks us to wait longer than this and no credential or model fallback succeeds, the request fails fast instead of sleeping (e.g. 3-hour Anthropic rate-limit windows). 0 disables the ceiling — to let the session auto-resume through provider-stated quota resets.": "重试之间的最大等待时间（毫秒）。当提供商要求等待时间超过此值且凭据或模型回退都不成功时，请求会快速失败而非休眠（如 Anthropic 3 小时限速窗口）。0 表示禁用上限——让会话通过提供商声明的配额重置自动恢复。",
  "Allow retry recovery to switch to configured fallback models": "允许重试恢复时切换到配置的备用模型",
  "Use reliable coding-plan quota reports to prefer same-provider accounts, then configured fallback models, before a hard usage limit. Ordinary configured API keys are excluded.": "在达到硬用量限制前，使用可靠的 coding-plan 配额报告优先选择同提供商账户，然后才是配置的备用模型。普通配置的 API 密钥被排除在外。",
  "Treat a coding-plan model as near its limit below this remaining percentage. Unknown or unmapped usage keeps the primary model.": "当 coding-plan 模型的剩余百分比低于此值时视为接近限额。未知或未映射的用量保留主模型。",
  "What to do when every same-provider coding-plan account is inside the reserve margin.": "当所有同提供商 coding-plan 账户都处于保留余量内时采取的操作。",
  "JSON object mapping model roles, model selectors (\"provider/model-id\"), or provider wildcards (\"provider/*\") to ordered fallback selectors, e.g. {\"default\":[\"openai/gpt-4o-mini\"],\"google-antigravity/*\":[\"google/*\",\"google-vertex/*\"]}. Model-oriented keys apply whenever that model/provider is active, regardless of role; a \"provider/*\" entry keeps the failing model's id and swaps the provider. An id-prefixed wildcard (\"openrouter/google/*\") re-prefixes the failing model's bare id (google-antigravity/gemini-x -> openrouter/google/gemini-x) and, used as a key, matches only that provider's ids under the prefix.": "将模型角色、模型选择器（\"provider/model-id\"）或提供商通配符（\"provider/*\"）映射到有序备用选择器的 JSON 对象。模型导向的键在该模型/提供商激活时应用，不论角色；\"provider/*\" 条目保留失败模型的 id 并交换提供商。id 前缀通配符（\"openrouter/google/*\"）重新前缀失败模型的裸 id，作为键时仅匹配该前缀下该提供商的 id。",
  "When to return to the primary model after a fallback": "回退后何时恢复主模型",
  "When a Claude Fable 5 / Mythos 5 request is blocked by Anthropic's safety classifier, retry it on Claude Opus 4.8 server-side (Anthropic `server-side-fallback-2026-06-01` beta). Opt-in — leaving this off preserves the pre-fallback behavior for every request.": "当 Claude Fable 5 / Mythos 5 请求被 Anthropic 安全分类器拦截时，在 Claude Opus 4.8 服务端重试（Anthropic `server-side-fallback-2026-06-01` beta）。选择启用——关闭则保留所有请求的回退前行为。",
  "How to process queued messages while agent is working": "智能体工作时如何处理排队消息",
  "How to drain follow-up messages after a turn completes": "一轮结束后如何排空后续消息",
  "When steering messages interrupt tool execution": "引导消息何时中断工具执行",
  "What happens between /loop iterations before re-submitting the prompt": "/loop 迭代之间在重新提交提示前发生什么",
  "What pressing Escape twice with an empty editor does: open the transcript rewind selector, open the session tree, or nothing": "在空编辑器中按两次 Escape 的操作：打开记录回退选择器、打开会话树，或什么都不做",
  "Default filter mode when opening the session tree": "打开会话树时的默认过滤模式",
  "Max visible items in autocomplete dropdown (3-20)": "自动完成下拉列表的最大可见项数（3-20）",
  "Mark misspelled prompt words with the active macOS dictionaries": "使用活动的 macOS 字典标记拼写错误的提示词",
  "Show macOS dictionary word completions as inline hints accepted with Tab": "将 macOS 字典单词补全显示为可用 Tab 接受的行内提示",
  "Apply confident macOS spelling corrections after completed words": "在完成后应用有把握的 macOS 拼写纠正",
  "Suggest emojis from `:name:` shortcodes and expand text emoticons like `:D` or `:-)`": "从 `:name:` 短代码建议 emoji 并展开 `:D` 或 `:-)` 等文本表情",
  "When a paste reaches this many lines, offer a menu to wrap it in a code block, wrap it in XML tags, or save it to a file. 0 disables the menu (large pastes still collapse to a [Paste] marker).": "当粘贴达到这么多行时，提供菜单选择用代码块包裹、用 XML 标签包裹或保存到文件。0 表示禁用菜单（大粘贴仍会折叠为 [Paste] 标记）。",
  "Skip welcome screen and startup status messages": "跳过欢迎屏幕和启动状态消息",
  "Show the full animated setup splash on normal interactive startup without rerunning setup. Quiet Startup still suppresses it.": "在正常交互启动时显示完整动画设置启动画面，无需重新运行设置。安静启动仍会抑制它。",
  "Show newly added onboarding steps once per setup version": "每个设置版本仅显示一次新添加的引导步骤",
  "Check for omp updates on startup": "启动时检查 omp 更新",
  "Update channel used by omp update and the startup update check": "omp 更新和启动更新检查使用的更新渠道",
  "Check for plugin updates on startup": "启动时检查插件更新",
  "Choose whether update notes start as a summary, full details, or stay hidden": "选择更新说明以摘要、完整详情还是隐藏状态开始",
  "Enable hidden notices for standalone ultrathink, orchestrate, and workflowz keywords": "为独立 ultrathink、orchestrate 和 workflowz 关键词启用隐藏通知",
  "Let standalone ultrathink request maximum automatic thinking and append its hidden notice": "让独立 ultrathink 请求最大自动思考并附加其隐藏通知",
  "Let standalone orchestrate append its hidden multi-agent orchestration notice": "让独立 orchestrate 附加其隐藏的多智能体编排通知",
  "Let standalone workflowz append its hidden eval workflow notice": "让独立 workflowz 附加其隐藏的工作流评估通知",
  "Notify when the agent finishes a turn": "智能体完成一轮时通知",
  "Notify when the agent stops with an error": "智能体因错误停止时通知",
  "Auto-select the recommended ask option after this many seconds (0 disables)": "在此秒数后自动选择推荐的询问选项（0 表示禁用）",
  "Notify when the ask tool is waiting for input": "ask 工具等待输入时通知",
  "Generate a brief LLM recap of where things stand after the terminal has been idle": "终端空闲后生成关于当前进展的简要 LLM 回顾",
  "Seconds to wait while idle before showing the recap": "空闲时等待多少秒后显示回顾",
  "Relay used by /collab (wss://host[:port])": "/collab 使用的中继（wss://host[:port]）",
  "Browser UI used by /collab links; empty derives from collab.relayUrl; explicit http:// is localhost-only": "/collab 链接使用的浏览器 UI；空则从 collab.relayUrl 派生；显式 http:// 仅限本地",
  "Name shown to other collab participants (default: OS username)": "显示给其他 collab 参与者的名称（默认：操作系统用户名）",
  "Share viewer/upload base used by /share (encrypted blob upload + viewer; links are <base>/<id>#<key>)": "/share 使用的共享查看/上传基础（加密 blob 上传 + 查看器；链接格式为 <base>/<id>#<key>）",
  "Where /share uploads the encrypted session blob": "/share 上传加密会话 blob 的位置",
  "Run the secret obfuscator over /share snapshots before upload (uses the secrets.* config)": "上传前对 /share 快照运行秘密混淆器（使用 secrets.* 配置）",
  "Enable speech-to-text input via microphone": "启用通过麦克风的语音转文字输入",
  "Local on-device speech model. Parakeet TDT v3 (sherpa-onnx) is the SoTA default; Whisper base/small/large-v3-turbo tiers (transformers.js) trade size for multilingual coverage. Downloaded on first use.": "本地设备端语音模型。Parakeet TDT v3（sherpa-onnx）是 SOTA 默认；Whisper base/small/large-v3-turbo 层级（transformers.js）以体积换取多语言覆盖。首次使用时下载。",
  "Choose when speech dictation automatically submits: Never, Release (2+ words), Release with complete sentence, or When I Say Submit.": "选择语音听写何时自动提交：从不、松开时（2+ 词）、松开且完整句子时，或我说提交时。",
  "Promote to a larger-context model on context overflow instead of compacting": "上下文溢出时升级到更大上下文模型而非压缩",
  "Use premium long-context windows on models that bill extra past a threshold (e.g. GPT-5.6 1M charges 2x input above 272K); off caps them at the standard-pricing window": "对超过阈值后额外计费的模型使用高级长上下文窗口（如 GPT-5.6 1M 在 272K 以上收取 2 倍输入）；关闭则限制在标准定价窗口",
  "Automatically compact context when it gets too large": "上下文过大时自动压缩",
  "Check thresholds at safe mid-turn tool-loop boundaries before the next provider request": "在下一个提供商请求前，在安全的回合中工具循环边界检查阈值",
  "Preferred fallback order for automatic context maintenance; unavailable or failed methods advance to the next choice": "自动上下文维护的首选回退顺序；不可用或失败的方法推进到下一个选项",
  "Percent threshold for context maintenance; set to Default to use legacy reserve-based behavior": "上下文维护的百分比阈值；设为 Default 则使用基于预留的传统行为",
  "Fixed token limit for context maintenance; overrides percentage if set": "上下文维护的固定 token 限制；设置后覆盖百分比",
  "Save generated handoff documents to markdown files for the auto-handoff flow": "为自动交接流保存生成的交接文档为 markdown 文件",
  "Use Responses streaming compaction for compatible remote compaction models": "对兼容的远程压缩模型使用 Responses 流式压缩",
  "Speculatively summarize in the background as context nears the compaction threshold, then splice the ready result in when the threshold is crossed": "当上下文接近压缩阈值时在后台推测性总结，阈值被突破时插入已就绪的结果",
  "Compact context while idle when token count exceeds threshold": "空闲时当 token 数超过阈值则压缩上下文",
  "Token count above which idle compaction triggers": "触发空闲压缩的 token 数阈值",
  "Seconds to wait while idle before compacting": "空闲时等待多少秒后压缩",
  "Prune older read results when the same file is read again (cache-aware, runs every turn)": "再次读取同一文件时修剪旧的读取结果（缓存感知，每轮运行）",
  "Prune tool results flagged contextually useless (no matches, timed-out waits) once consumed (cache-aware)": "修剪被标记为上下文无用的工具结果（无匹配、等待超时）一旦消耗后（缓存感知）",
  "Experimental: render selected system prompt text as dense PNG image(s) and attach to the first user message (vision models only). Saves tokens; loses prompt caching for imaged text.": "实验性：将选定的系统提示文本渲染为密集 PNG 图片并附加到第一条用户消息（仅视觉模型）。节省 token；图片化文本会丢失提示缓存。",
  "Experimental: render large historical tool results as dense PNG image(s) instead of text (vision models only). Saves tokens on accumulated read/search output.": "实验性：将大型历史工具结果渲染为密集 PNG 图片而非文本（仅视觉模型）。在累积的读取/搜索输出上节省 token。",
  "Controls how tools are exposed to the model. Auto uses provider-native tool calls unless the selected model is marked as not supporting them, then falls back to the GLM owned dialect. Native forces provider-native tools; the other values force the named owned dialect. Applies on session start.": "控制工具如何暴露给模型。auto 使用提供商原生工具调用，除非所选模型标记为不支持，则回退到 GLM 自有方言。Native 强制使用提供商原生工具；其他值强制使用命名的自有会话启动时应用。",
  "Frame shape snapcompact prints text with (compaction archive and inline imaging). Auto picks a shape tuned for the current model.": "帧形状 snapcompact 打印文本（压缩存档和内联成像）。auto 选择为当前模型调优的形状。",
  "Prompt to summarize when leaving a branch": "离开分支时用于总结的提示词",
  "Off, local summary pipeline, Mnemopi SQLite, Hindsight remote memory, or Sharpshooter": "关闭、本地摘要流水线、Mnemopi SQLite、Hindsight 远程记忆或 Sharpshooter",
  "Model selector for extraction/consolidation, empty = smol role": "提取/合并的模型选择器，空 = smol 角色",
  "After the agent stops, nudge it to capture lessons to memory and create/enhance isolated managed skills": "智能体停止后，引导其将经验捕获到记忆并创建/增强隔离的托管技能",
  "When on, auto-run one private capture turn at stop (uses extra tokens). When off, only standing auto-learn guidance remains.": "开启时，停止时自动运行一个私有捕获轮次（消耗额外 token）。关闭时，仅保留常设的自动学习引导。",
  "Optional SQLite DB path. Defaults to the agent memories directory.": "可选的 SQLite 数据库路径。默认为智能体记忆目录。",
  "Optional shared bank base name. Per-project modes derive project-local banks from it.": "可选的共享库基础名称。按项目模式从中派生项目本地库。",
  "global = one shared bank; per-project = isolated bank per cwd; per-project-tagged = project-local writes plus global recall visibility": "global = 一个共享库；per-project = 每个 cwd 一个隔离库；per-project-tagged = 项目本地写入加上全局召回可见性",
  "Local embedding model family. en = stronger English model; multilingual = cross-language model. Changing this rebuilds existing memory embeddings on next start.": "本地嵌入模型族。en = 更强的英语模型；multilingual = 跨语言模型。更改此值会在下次启动时重建现有记忆嵌入。",
  "Recall local memories into the first turn of each session": "在每个会话的第一轮召回本地记忆",
  "Retain completed conversation turns into local Mnemopi memory": "将已完成的对话轮次保留到本地 Mnemopi 记忆中",
  "Enable 4-voice recall (vector, graph, fact, temporal) fused with reciprocal rank fusion": "启用 4 路召回（向量、图、事实、时间）与互惠排名融合",
  "Enable the tiered query result cache for repeated and similar recall queries": "为重复和相似的召回查询启用分层查询结果缓存",
  "Ingest new memories into the episodic graph as they are stored, linking them to related entities and memories": "将新记忆存储到时序图中时，将其链接到相关实体和记忆",
  "Force deterministic FTS-only recall instead of vector embeddings": "强制使用确定性纯 FTS 召回而非向量嵌入",
  "Advanced: explicit embedding model id that overrides the variant. Leave empty to use mnemopi.embeddingVariant.": "高级：覆盖变体的显式嵌入模型 id。留空则使用 mnemopi.embeddingVariant。",
  "Optional OpenAI-compatible embedding endpoint passed to Mnemopi": "传递给 Mnemopi 的可选 OpenAI 兼容嵌入端点",
  "Optional embedding API key passed to Mnemopi": "传递给 Mnemopi 的可选嵌入 API 密钥",
  "Use no LLM, the online tiny model (the TINY role from /models, else @smol), or a remote OpenAI-compatible endpoint": "不使用 LLM、在线 tiny 模型（来自 /models 的 TINY 角色，否则 @smol），或远程 OpenAI 兼容端点",
  "Optional OpenAI-compatible LLM endpoint for Mnemopi remote mode": "Mnemopi 远程模式的可选 OpenAI 兼容 LLM 端点",
  "Optional LLM API key for Mnemopi remote mode": "Mnemopi 远程模式的可选 LLM API 密钥",
  "Optional LLM model name for Mnemopi remote mode": "Mnemopi 远程模式的可选 LLM 模型名称",
  "Hindsight server URL (Cloud or self-hosted)": "Hindsight 服务器 URL（云端或自托管）",
  "Bearer token for authenticated Hindsight servers": "已认证 Hindsight 服务器的 Bearer 令牌",
  "Memory bank identifier (default: project name)": "记忆库标识符（默认：项目名称）",
  "global = one shared bank; per-project = isolated bank per cwd; per-project-tagged = shared bank with project tags so global + project memories merge on recall": "global = 一个共享库；per-project = 每个 cwd 一个隔离库；per-project-tagged = 带项目标签的共享库，召回时合并全局和项目记忆",
  "Recall memories on the first turn of each session": "在每个会话的第一轮召回记忆",
  "Retain transcript every N turns and at session boundaries": "每 N 轮和会话边界保留记录",
  "full-session = upsert one document per session, last-turn = chunked": "full-session = 每个会话 upsert 一个文档，last-turn = 分块",
  "Read curated reflect summaries (mental models) into developer instructions at boot. Loads existing models on the bank — does not write. Pair with hindsight.mentalModelAutoSeed to also auto-create the built-in seed set.": "启动时将策划的 reflect 摘要（心智模型）读入开发者指令。加载库上已有的模型——不写入。与 hindsight.mentalModelAutoSeed 搭配可自动创建内置种子集。",
  "At session start, create any built-in mental models (project-conventions, project-decisions, user-preferences) that do not yet exist on the bank.": "在会话开始时，创建库上尚不存在的心智模型（项目约定、项目决策、用户偏好）。",
  "Interrupt the agent mid-stream when output matches rule patterns (Time-Traveling Stream Rules)": "当输出匹配规则模式时中断智能体流（时间旅行流规则）",
  "What to do with partial output when TTSR triggers": "TTSR 触发时如何处理部分输出",
  "When to interrupt mid-stream vs inject warning after completion": "何时中断流 vs 完成后注入警告",
  "How rules can repeat: once per session or after a message gap": "规则如何重复：每个会话一次或在消息间隔后",
  "Messages before a rule can trigger again": "规则再次触发前的消息数",
  "Load the default rules shipped with the agent (override individually with ttsr.disabledRules)": "加载智能体附带的默认规则（可用 ttsr.disabledRules 单独覆盖）",
  "Rule names to ignore entirely (applies to bundled defaults and your own rules)": "完全忽略的规则名称（适用于捆绑默认规则和你自己的规则）",
  "Select the edit tool variant (replace, patch, hashline, or apply_patch)": "选择编辑工具变体（replace、patch、hashline 或 apply_patch）",
  "Accept high-confidence fuzzy matches for whitespace differences": "接受针对空白差异的高置信度模糊匹配",
  "Similarity threshold (0-1) for accepting fuzzy matches": "接受模糊匹配的相似度阈值（0-1）",
  "Abort streaming edit tool calls when patch preview fails": "补丁预览失败时中止流式编辑工具调用",
  "Execute edit payloads the model emits as plain text by converting them into edit tool calls": "通过将模型以纯文本发出的编辑负载转换为编辑工具调用来执行",
  "Prevent editing of files that appear to be auto-generated (protoc, sqlc, swagger, etc.)": "阻止编辑看起来是自动生成的文件（protoc、sqlc、swagger 等）",
  "Reject edits anchored on lines a prior read/search never displayed in full": "拒绝基于先前读取/搜索从未完整显示的行的编辑",
  "Append full before/after source when an edit introduces an AST parse failure": "当编辑引入 AST 解析失败时，附加完整的前后源代码",
  "When an edit breaks a file's AST parse, ask the smol model to fix the broken region (validated by re-parse; falls back to a warning)": "当编辑破坏文件的 AST 解析时，让 smol 模型修复损坏区域（通过重新解析验证；失败则回退到警告）",
  "Prepend line numbers to read tool output by default": "默认在读取工具输出前添加行号",
  "Default number of lines returned when agent calls read without a limit": "智能体调用 read 未指定限制时返回的默认行数",
  "Render Markdown read results as formatted terminal Markdown previews instead of raw source": "将 Markdown 读取结果渲染为格式化的终端 Markdown 预览而非原始源码",
  "Return structural code summaries when read is called without an explicit selector": "调用 read 未指定选择器时返回结构化代码摘要",
  "Return structural summaries for Markdown and plain text reads": "为 Markdown 和纯文本读取返回结构化摘要",
  "Minimum multiline body or literal length before read summaries collapse it": "读取摘要折叠前的最小多行体或字面量长度",
  "Minimum multiline block comment length before read summaries collapse it": "读取摘要折叠前的最小多行块注释长度",
  "Files with fewer total lines are read verbatim instead of structurally summarized": "总行数少于该值的文件按原样读取而非结构化摘要",
  "BFS-unfold elidable spans until the summary is at least this many visible lines. 0 keeps only the outermost elisions.": "BFS 展开可折叠范围，直到摘要至少有这么多可见行。0 表示仅保留最外层折叠。",
  "Hard ceiling on summary size while BFS-unfolding. An unfold whose revealed lines would exceed this is skipped (that span stays folded) and unfolding continues with the remaining spans.": "BFS 展开时摘要大小的硬上限。若展开揭示的行数会超过此值则跳过（该范围保持折叠）并继续展开其余范围。",
  "Render read tool results inline in the transcript instead of summary rows": "在记录中内联渲染读取工具结果而非摘要行",
  "Enable the lsp tool for code intelligence (definitions, references, diagnostics, rename)": "启用 lsp 工具用于代码智能（定义、引用、诊断、重命名）",
  "Start language servers on first use (lsp tool or editing a matching file type) instead of at session startup": "首次使用时启动语言服务器（lsp 工具或编辑匹配文件类型）而非在会话启动时",
  "Share one language server per project across omp instances via the daemon broker (falls back to private servers when unavailable)": "通过守护进程代理在 omp 实例间每个项目共享一个语言服务器（不可用时回退到私有服务器）",
  "Automatically format code files using LSP after writing": "写入后使用 LSP 自动格式化代码文件",
  "Return LSP diagnostics after writing code files": "写入代码文件后返回 LSP 诊断",
  "Return LSP diagnostics after editing code files": "编辑代码文件后返回 LSP 诊断",
  "Suppress post-edit LSP diagnostics already shown for a file; only surface new or changed ones": "抑制已为该文件显示过的编辑后 LSP 诊断；仅显示新的或更改的",
  "Enable the bash tool for shell command execution": "启用 bash 工具用于 shell 命令执行",
  "Automatically background long-running bash commands and deliver the result later": "自动将长时间运行的 bash 命令放入后台并稍后交付结果",
  "Ordered bash command approval rules. Each item has match and approval fields; only '*' wildcards are supported.": "有序的 bash 命令审批规则。每项有 match 和 approval 字段；仅支持 '*' 通配符。",
  "Block shell commands that have dedicated tools": "阻止有专用工具的 shell 命令",
  "Auto-load a repo's direnv/devenv `.envrc` into the bash session so devenv tools and env vars are present without manual `direnv exec`. Honors direnv's allow list: an `.envrc` you haven't `direnv allow`ed is never executed": "自动将仓库的 direnv/devenv `.envrc` 加载到 bash 会话中，使 devenv 工具和环境变量无需手动 `direnv exec` 即可使用。遵守 direnv 允许列表：未 `direnv allow` 的 `.envrc` 永远不会执行",
  "Max wait for the first `direnv export` (a cold devenv shell can be slow); on timeout the session runs without the direnv env": "首次 `direnv export` 的最大等待时间（冷启动 devenv shell 可能较慢）；超时后会话在没有 direnv 环境的情况下运行",
  "Compress verbose shell output (git, npm, cargo, etc.) before returning it to the agent": "在返回给智能体前压缩冗长的 shell 输出（git、npm、cargo 等）",
  "Source outline mode for cat/read of source files: default or aggressive": "源码文件 cat/read 的源码大纲模式：default 或 aggressive",
  "Allow the eval tool to dispatch Python cells to the IPython kernel": "允许 eval 工具将 Python 单元分派到 IPython 内核",
  "Allow the eval tool to dispatch JavaScript cells to the in-process runtime": "允许 eval 工具将 JavaScript 单元分派到进程内运行时",
  "Let eval cells define tools (@tool in Python, tool(fn) in JS) that task, agent(), and workpool() subagents can call": "让 eval 单元定义工具（Python 中 @tool，JS 中 tool(fn)），供 task、agent() 和 workpool() 子智能体调用",
  "Spawn a new subagent for every workpool item instead of reusing workers or batching queued items": "为每个 workpool 项生成新子智能体，而非重用工作器或批量处理排队项",
  "Automatically background long-running eval cells and deliver the result later": "自动将长时间运行的 eval 单元放入后台并稍后交付结果",
  "Keep the IPython kernel alive across eval calls or start fresh each time": "在 eval 调用间保持 IPython 内核存活或每次重新启动",
  "Optional path to an exact Python executable. When set, automatic Python runtime discovery is skipped.": "可选的精确 Python 可执行文件路径。设置后跳过自动 Python 运行时发现。",
  "Per-tool approval policies. Set to 'allow' to auto-approve, 'prompt' to require confirmation, or 'deny' to block. Overrides are honored in every approval mode.": "每个工具的审批策略。设为 'allow' 自动批准，'prompt' 需要确认，'deny' 阻止。覆盖规则在所有审批模式下生效。",
  "Default approval behavior for tool calls. 'Always ask' auto-approves read-only tools only. 'Write' auto-approves read and workspace-write tools. 'Yolo' auto-approves all tiers; user policy may still prompt or block.": "工具调用的默认审批行为。'Always ask' 仅自动批准只读工具。'Write' 自动批准读取和工作区写入工具。'Yolo' 自动批准所有层级；用户策略仍可提示或阻止。",
  "Enable the todo tool for task tracking": "启用 todo 工具用于任务跟踪",
  "Remind the agent to complete todos before stopping": "提醒智能体在停止前完成待办",
  "Maximum number of todo reminders before giving up": "放弃前的最大待办提醒次数",
  "How strongly to push automatic todo-list creation after the first message": "第一条消息后推动自动创建待办清单的强度",
  "Enable the glob tool for glob-based file lookup": "启用 glob 工具用于基于 glob 的文件查找",
  "Enable the grep tool for regex content search": "启用 grep 工具用于正则内容搜索",
  "Lines of context before each grep match": "每个 grep 匹配前的上下文行数",
  "Lines of context after each grep match": "每个 grep 匹配后的上下文行数",
  "Enable the ast_grep tool for structural AST search": "启用 ast_grep 工具用于结构化 AST 搜索",
  "Enable the ast_edit tool for structural AST rewrites": "启用 ast_edit 工具用于结构化 AST 重写",
  "Enable the debug tool for DAP-based debugging": "启用 debug 工具用于基于 DAP 的调试",
  "Enable the launch tool for supervising shared long-running project processes": "启用 launch 工具用于监督共享的长时间运行项目进程",
  "Enable the tts tool for on-device (Kokoro) or xAI Grok Voice speech-file synthesis": "启用 tts 工具用于设备端（Kokoro）或 xAI Grok Voice 语音文件合成",
  "Enable the generate_image tool (text-to-image generation and editing). Exposed as an xd:// device when tools.xdev is on.": "启用 generate_image 工具（文本到图像生成和编辑）。当 tools.xdev 开启时暴露为 xd:// 设备。",
  "Controls the inspect_image tool, which delegates image understanding to a vision-capable model. 'auto' exposes it only when the active model lacks native image input; 'on' always exposes it; 'off' never does.": "控制 inspect_image 工具，将图像理解委托给视觉模型。'auto' 仅在当前模型缺乏原生图像输入时暴露；'on' 始终暴露；'off' 从不暴露。",
  "Enable the scriptable host-desktop control tool (screenshots, input, accessibility)": "启用可脚本化的主机桌面控制工具（截图、输入、无障碍）",
  "Composite all displays or select a native display id": "合成所有显示器或选择原生显示器 id",
  "Maximum composite screenshot width in pixels": "最大合成截图宽度（像素）",
  "Maximum composite screenshot height in pixels": "最大合成截图高度（像素）",
  "Per-request timeout for the inspect_image vision-model call, in milliseconds. A stalled provider fails fast with a timeout error instead of blocking until manual abort. Set to 0 to disable the timeout.": "inspect_image 视觉模型调用的每次请求超时（毫秒）。停滞的提供商快速失败并返回超时错误，而非阻塞直到手动中止。设为 0 禁用超时。",
  "Enable the checkpoint and rewind tools for context checkpointing": "启用 checkpoint 和 rewind 工具用于上下文检查点",
  "Allow the read tool to fetch and process URLs": "允许 read 工具获取和处理 URL",
  "Enable the vault:// internal URL for reading and editing Obsidian vault content via the Obsidian CLI. When disabled, vault:// resolution is refused and the vault:// entry is omitted from the system prompt.": "启用 vault:// 内部 URL 用于通过 Obsidian CLI 读取和编辑 Obsidian vault 内容。禁用时，vault:// 解析被拒绝，vault:// 条目从系统提示中省略。",
  "Enable the github tool (op-based dispatch for repository, issue, pull request, diff, search, checkout, push, and Actions watch workflows)": "启用 github 工具（基于 op 分派仓库、issue、pull request、diff、搜索、checkout、push 和 Actions watch 工作流）",
  "Cache rendered issue/PR view output in ~/.omp/cache/github-cache.db so repeated reads are free": "将渲染的 issue/PR 视图输出缓存到 ~/.omp/cache/github-cache.db 使重复读取免费",
  "Within this window, cached issue/PR view rows are returned directly (seconds; default 5 minutes)": "在此窗口内，缓存的 issue/PR 视图行直接返回（秒；默认 5 分钟）",
  "Past the soft TTL the cached row is returned and refreshed in the background; past the hard TTL it is dropped (seconds; default 7 days)": "超过软 TTL 时返回缓存行并在后台刷新；超过硬 TTL 时丢弃（秒；默认 7 天）",
  "Enable the web_search tool for live web results": "启用 web_search 工具用于实时网络结果",
  "Enable OMP-native security scan planning, execution, and the read-only security:// resource namespace": "启用 OMP 原生安全扫描规划、执行和只读 security:// 资源命名空间",
  "Enable the ask tool for interactive user questions": "启用 ask 工具用于交互式用户提问",
  "Enable the browser tool for scripted Chromium automation (puppeteer)": "启用 browser 工具用于脚本化 Chromium 自动化（puppeteer）",
  "Default HTTP CDP discovery endpoint (for example http://127.0.0.1:9222) to attach to instead of launching a browser. Explicit app.cdp_url or app.path on the tool call take precedence.": "默认 HTTP CDP 发现端点（如 http://127.0.0.1:9222）用于附加而非启动浏览器。工具调用上显式的 app.cdp_url 或 app.path 优先。",
  "Drive your own Chrome tabs through the omp browser relay. Install the extension once (`omp browser-relay install`); the relay server auto-starts when the browser tool needs it. Takes precedence over Browser CDP URL; set PI_BROWSER_RELAY=0 or PI_BROWSER_RELAY=1 to override.": "通过 omp 浏览器中继驱动你自己的 Chrome 标签页。安装一次扩展（`omp browser-relay install`）；当中继服务器需要时自动启动。优先于浏览器 CDP URL；设置 PI_BROWSER_RELAY=0 或 PI_BROWSER_RELAY=1 覆盖。",
  "omp browser relay endpoint (default http://127.0.0.1:9224).": "omp 浏览器中继端点（默认 http://127.0.0.1:9224）。",
  "Launch browser in headless mode (disable to show browser UI)": "以无头模式启动浏览器（禁用则显示浏览器 UI）",
  "Use cmux WKWebView surfaces for browser automation when a cmux socket is available. Set PI_BROWSER_CMUX=0 or PI_BROWSER_CMUX=1 to override.": "当 cmux 套接字可用时使用 cmux WKWebView 表面进行浏览器自动化。设置 PI_BROWSER_CMUX=0 或 PI_BROWSER_CMUX=1 覆盖。",
  "Directory to save screenshots. If unset, screenshots go to a temp file. Supports ~. Examples: ~/Downloads, ~/Desktop, /sdcard/Download (Android)": "保存截图的目录。未设置时截图保存到临时文件。支持 ~。示例：~/Downloads、~/Desktop、/sdcard/Download（Android）",
  "Ask the agent to describe the intent of each tool call before executing it": "在执行前要求智能体描述每次工具调用的意图",
  "With in-band tool calls, stop the model immediately when it starts hallucinating a tool result mid-turn. Disable to let the model finish generating and discard the fabricated continuation instead.": "对于带内工具调用，当模型在轮次中开始幻觉工具结果时立即停止。禁用则让模型完成生成并丢弃伪造的续写。",
  "Maximum timeout in seconds the agent can set for any tool (0 = no limit)": "智能体可为任何工具设置的最大超时秒数（0 = 无限制）",
  "Enable async bash commands and background task execution": "启用异步 bash 命令和后台任务执行",
  "How long a `hub` wait watches background jobs before returning the current state. A fixed value waits that exact duration every time. `smart` adapts: it starts at 5s and lengthens with each back-to-back wait (up to 5m), then resets to 5s after about a minute without waiting.": "`hub` 等待在返回当前状态前观察后台任务的时间。固定值每次都等待该确切时长。`smart` 自适应：从 5 秒开始，每次连续等待加长（最多 5 分钟），然后在约一分钟后无等待时重置为 5 秒。",
  "Default timeout for hub message waits (and send await:true) in milliseconds; 0 disables the timeout": "hub 消息等待（和 send await:true）的默认超时（毫秒）；0 表示禁用超时",
  "Mount rarely-used (discoverable) tools under xd:// device URLs driven via read/write instead of shipping their schemas on every request. Sessions whose explicit tool list grants read but omits write mount devices through a device-only write transport (filesystem writes stay rejected). Disable to expose every enabled tool top-level.": "将很少使用（可发现）的工具挂载到 xd:// 设备 URL 下通过 read/write 驱动，而非每次请求都发送其模式。显式工具列表授予读取但省略写入的会话通过仅设备写入传输挂载设备（文件系统写入仍被拒绝）。禁用则暴露所有已启用工具的顶层。",
  "Choose which mounted-device docs and schemas are inlined in the system prompt. Built-ins keeps core tools inline while MCP and extension tools stay on-demand.": "选择哪些挂载设备文档和模式内联到系统提示中。Built-ins 保持核心工具内联，而 MCP 和扩展工具保持按需。",
  "When xd:// Prompt Docs is Built-ins Only, inline dynamic devices whose names match these glob patterns (for example mcp__context_mode_*). Catalog Only ignores this setting.": "当 xd:// Prompt Docs 为仅内置时，内联名称匹配这些 glob 模式的动态设备（如 mcp__context_mode_*）。Catalog Only 忽略此设置。",
  "Load .mcp.json/mcp.json from project root": "从项目根目录加载 .mcp.json/mcp.json",
  "Render non-JSON MCP text results as Markdown in the transcript": "在记录中将非 JSON MCP 文本结果渲染为 Markdown",
  "Inject MCP resource updates into the agent conversation": "将 MCP 资源更新注入到智能体会话中",
  "Debounce window in milliseconds for MCP resource updates before injecting them into the conversation": "在将 MCP 资源更新注入会话前的防抖窗口（毫秒）",
  "Enable plan mode for read-only exploration and planning before execution": "启用计划模式用于执行前的只读探索和规划",
  "Automatically enter plan mode at the start of every new session": "在每个新会话开始时自动进入计划模式",
  "Enable per-session goal mode and the hidden goal tool": "启用每会话目标模式和隐藏目标工具",
  "Show token budget alongside the goal indicator in the status line": "在状态行中目标指示器旁显示 token 预算",
  "Run modes where active goals may auto-continue between turns": "活动目标可在轮次间自动继续的运行模式",
  "Refresh generated session titles after todo init replans unless the title was set by the user": "在 todo 初始化重计划后刷新生成的会话标题，除非标题由用户设置",
  "Run subagents in an isolated copy of the checkout and integrate their changes afterwards": "在检出的隔离副本中运行子智能体，之后整合其更改",
  "Backend used for subagent isolation and worktree cloning": "用于子智能体隔离和工作树克隆的后端",
  "New worktrees from `github pr_checkout` and `git worktree add` in bash start as a copy-on-write clone of the current checkout so ignored build artifacts (node_modules, target) carry over; falls back to a plain checkout when the filesystem cannot clone": "来自 `github pr_checkout` 和 bash 中 `git worktree add` 的新工作树作为当前检出的写时复制克隆启动，使被忽略的构建产物（node_modules、target）得以保留；当文件系统无法克隆时回退到普通检出",
  "Automatically apply successful isolated task changes to the parent checkout; disable to retain patch or branch artifacts": "自动将成功的隔离任务更改应用到父检出；禁用则保留补丁或分支构件",
  "How isolated task changes are integrated (patch apply or branch merge)": "隔离任务更改如何整合（补丁应用或分支合并）",
  "Commit message style for nested repo changes (generic or AI-generated)": "嵌套仓库更改的提交消息风格（通用或 AI 生成）",
  "Base directory for agent-managed worktrees — task-isolation copies, `github` PR checkouts, and `omp worktree` cleanup all live here. Unset uses ~/.omp/wt. Must be an absolute or ~-relative path; relative paths are ignored. The OMP_WORKTREE_DIR env var overrides this.": "智能体管理的工作树的基础目录——任务隔离副本、`github` PR 检出和 `omp worktree` 清理都在此处。未设置使用 ~/.omp/wt。必须是绝对路径或 ~-相对路径；相对路径被忽略。OMP_WORKTREE_DIR 环境变量覆盖此值。",
  "How strongly to push delegating work to subagents": "推动将工作委托给子智能体的强度",
  "Switch the task tool to its batch shape: one call carries { context, tasks[] } — one subagent per item, with an optional per-item agent (defaulting to the session spawn-policy agent), per-item isolation, and a required shared context prepended to every assignment. With async.enabled=true, each spawn runs as an independent background agent with the normal idle/parked lifecycle; otherwise the call blocks for merged results. Disable to restore the flat single-spawn schema.": "将任务工具切换到其批量形态：一次调用携带 { context, tasks[] }——每项一个子智能体，可选每项智能体（默认为会话生成策略智能体），每项隔离，以及每个任务前附加必需的共享上下文。当 async.enabled=true 时，每次生成作为独立后台智能体运行，具有正常的空闲/停放生命周期；否则调用阻塞等待合并结果。禁用则恢复扁平单次生成模式。",
  "Expose the optional effort parameter on task spawns, allowing callers to override each subagent's thinking level": "在任务生成时暴露可选的 effort 参数，允许调用者覆盖每个子智能体的思考等级",
  "Maximum number of subagents running concurrently": "并发运行的最大子智能体数",
  "Allow subagents spawned via the task tool to use the lsp tool. Off by default to keep subagents cheap; enable when LSP-aware delegation is worth the extra tokens.": "允许通过 task 工具生成的子智能体使用 lsp 工具。默认关闭以保持子智能体轻量；当 LSP 感知的委托值得额外 token 时启用。",
  "How many levels deep subagents can spawn their own subagents": "子智能体可以生成自己子智能体的深度层数",
  "Hard wall-clock limit per subagent (ms). 0 disables it. Defense-in-depth against provider-side stream hangs that escape the inference-layer watchdog; triggers a normal subagent abort with a 'timed out' reason.": "每个子智能体的硬时钟限制（毫秒）。0 表示禁用。针对逃脱推理层看门狗的提供商端流挂起的纵深防御；以「超时」原因触发正常子智能体中止。",
  "How long an idle subagent stays live in memory before being parked to disk (ms). Parked agents are revived automatically when messaged or resumed. 0 keeps idle agents live until exit.": "空闲子智能体在内存中保持存活多长时间后停放磁盘（毫秒）。停放智能体在收到消息或恢复时自动复活。0 表示空闲智能体保持存活直到退出。",
  "Soft per-subagent request budget (assistant requests per run). Crossing it injects a wrap-up steering notice (see task.softRequestBudgetNotice); at 1.5x the budget the run is force-stopped and the agent must yield its partial findings. 0 disables the guard. Bundled scout/sonic agents cap out at a lower built-in budget, so a value below that cap still applies to them.": "每个子智能体的软请求预算（每次运行的助手请求数）。超过它会注入收尾引导通知（见 task.softRequestBudgetNotice）；达到预算 1.5 倍时运行被强制停止，智能体必须交出部分发现。0 表示禁用守护。捆绑的 scout/sonic 智能体在较低的内建预算处封顶，因此低于该封顶的值仍适用于它们。",
  "Inject one steering notice when a subagent crosses its soft request budget, asking it to wrap up before the 1.5x forced-yield stop.": "当子智能体超过其软请求预算时注入一个引导通知，要求它在 1.5 倍强制交出停止前收尾。",
  "Maximum reasoning effort allowed for the task tool's per-spawn effort hint. Lower values prevent callers from escalating subagents above this ceiling; the default preserves the model's full range.": "任务工具每次生成 effort 提示允许的最大推理力度。较低值防止调用者将子智能体升级到超过此上限；默认保留模型的完整范围。",
  "Arm prewalk for the bundled generic `task` subagent: it starts on its resolved model, plans and begins the implementation, then hands off to the 'smol' role at its first edit/write. Per-agent overrides (task.agentPrewalk, configured from the /agents hub) and user agent `prewalk` frontmatter apply regardless of this toggle.": "为捆绑的通用 `task` 子智能体装备 prewalk：它在其解析的模型上启动，规划并开始实现，然后在首次编辑/交出控制权给 'smol' 角色。每智能体覆盖（task.agentPrewalk，从 /agents 中心配置）和用户智能体 `prewalk` 前置事项无论此开关如何都应用。",
  "Delay before completed or abandoned todos are removed from the todo widget": "已完成或放弃的待办从待办小部件移除前的延迟",
  "Display the actual model ID used by each subagent in the task widget status line": "在任务小部件状态行中显示每个子智能体使用的实际模型 ID",
  "Register skills as /skill:name commands": "将技能注册为 /skill:name 命令",
  "Load commands from ~/.claude/commands/": "从 ~/.claude/commands/ 加载命令",
  "Load commands from .claude/commands/": "从 .claude/commands/ 加载命令",
  "Load commands from ~/.config/opencode/commands/": "从 ~/.config/opencode/commands/ 加载命令",
  "Load commands from .opencode/commands/": "从 .opencode/commands/ 加载命令",
  "Obfuscate configured secrets and redact credential-shaped tokens before sending to AI providers": "在发送给 AI 提供商前混淆配置的凭据并编辑凭证形状的令牌",
  "Maximum concurrent Ollama Cloud subagent runs per process; 0 disables the provider-specific limit": "每个进程的最大并发 Ollama Cloud 子智能体运行数；0 表示禁用提供商特定限制",
  "Prioritized providers for the web_search tool; unlisted providers retain their default order afterward": "web_search 工具的优先提供商；未列出的提供商之后保留其默认顺序",
  "Providers that web_search should never use, even as fallbacks": "web_search 永远不应使用的提供商，即使作为回退",
  "Hard timeout for each provider's search transport before web_search advances to the next fallback, in seconds (maximum 300)": "web_search 推进到下一个回退前每个提供商搜索传输的硬超时（秒；最大 300）",
  "Model ID for Gemini Google Search grounding. Defaults to gemini-2.5-flash.": "Gemini Google Search 基础的模型 ID。默认为 gemini-2.5-flash。",
  "Endpoint routing strategy for google-antigravity providers (chat, search, image, discovery)": "google-antigravity 提供商的端点路由策略（聊天、搜索、图像、发现）",
  "Prioritized providers for image generation; unlisted providers follow the active session provider and the built-in order": "图像生成的优先提供商；未列出的提供商跟随当前会话提供商和内置顺序",
  "Serving path for Fireworks requests. Priority sends `service_tier: \"priority\"` for higher reliability during peak traffic at a higher price; Standard omits it. Fast (`-fast`) models ignore this — Fast is its own serving path.": "Fireworks 请求的服务路径。Priority 发送 `service_tier: \"priority\"` 以在高峰流量时获得更高可靠性，价格更高；Standard 省略它。Fast（`-fast`）模型忽略此设置——Fast 是它自己的服务路径。",
  "Voice used by Codex-backed realtime voice sessions": "Codex 支持的实时语音会话使用的语音",
  "Backend for the tts tool: local on-device neural TTS (Kokoro-82M), xAI Grok Voice, or DeepInfra speech": "tts 工具的后端：本地设备端神经 TTS（Kokoro-82M）、xAI Grok Voice 或 DeepInfra 语音",
  "On-device neural TTS model (Kokoro-82M) used by the local TTS backend": "本地 TTS 后端使用的设备端神经 TTS 模型（Kokoro-82M）",
  "Kokoro voice used by the local TTS backend (American/British, female/male)": "本地 TTS 后端使用的 Kokoro 语音（美式/英式、女声/男声）",
  "Speak the assistant's output aloud through the speakers as it streams": "在流式输出时通过扬声器朗读助手输出",
  "What to speak: all = assistant messages + thinking; assistant = messages only; yield = only the final message at turn end": "朗读内容：all = 助手消息 + 思考；assistant = 仅消息；yield = 仅轮次结束时的最终消息",
  "Rewrite assistant output into natural spoken prose with the tiny/smol model before synthesis (describes code, drops links and markdown). Falls back to mechanical cleanup on failure": "在合成前用 tiny/smol 模型将助手输出重写为自然口语散文（描述代码、去掉链接和 markdown）。失败时回退到机械清理",
  "Kokoro voice used when speaking the assistant's output aloud": "朗读助手输出时使用的 Kokoro 语音",
  "Session-title model: online (the TINY role from /models, else @smol) by default, or a local on-device model": "会话标题模型：默认在线（来自 /models 的 TINY 角色，否则 @smol），或本地设备端模型",
  "Inference backend for local tiny models (titles + memory): an ONNX execution provider, or `mlx` to download MLX weights and run them through mlx-lm on Apple silicon. Default uses CPU-only ONNX. The PI_TINY_DEVICE env var overrides this.": "本地 tiny 模型（标题 + 记忆）的推理后端：ONNX 执行提供程序，或 `mlx` 下载 MLX 权重并在 Apple 芯片上通过 mlx-lm 运行。默认使用仅 CPU 的 ONNX。PI_TINY_DEVICE 环境变量覆盖此值。",
  "ONNX quantization/precision for local tiny models. Default uses each model's shipped dtype (q4); lower precision is faster, higher is more faithful. Ignored by the MLX backend (its repos are pre-quantized 4-bit). The PI_TINY_DTYPE env var overrides this.": "本地 tiny 模型的 ONNX 量化/精度。默认使用每个模型附带的 dtype（q4）；精度越低越快，越高越忠实。MLX 后端忽略此设置（其仓库已预量化为 4 位）。PI_TINY_DTYPE 环境变量覆盖此值。",
  "Mnemopi LLM for fact extraction + consolidation: online (the TINY role from /models, else smol/remote) by default, or a local on-device model": "用于事实提取 + 合并的 Mnemopi LLM：默认在线（来自 /models 的 TINY 角色，否则 smol/远程），或本地设备端模型",
  "Difficulty classifier for the `auto` thinking level: online (the TINY role from /models, else smol) by default, or a local on-device model": "`auto` 思考等级的难度分类器：默认在线（来自 /models 的 TINY 角色，否则 smol），或本地设备端模型",
  "Highest effort the `auto` classifier may resolve. `xhigh` keeps the classifier one tier below the top, so only an explicit `ultrathink` reaches `max`; `max` lets a turn the classifier judges exceptional bill the top tier on models that expose it.": "`auto` 分类器可解析的最高力度。`xhigh` 使分类器保持在最高级以下一档，因此只有显式的 `ultrathink` 才能达到 `max`；`max` 让分类器判断为杰出的轮次在暴露该级别的模型上计费最高档。",
  "Automatically recover when the assistant stops without a visible message. Smart also classifies text-only stops with a small model.": "当助手停止但没有可见消息时自动恢复。Smart 还会用小模型对纯文本停止进行分类。",
  "Classifier for Smart unexpected-stop detection: online (the TINY role from /models, else smol) by default, or a local on-device model.": "Smart 意外停止检测的分类器：默认在线（来自 /models 的 TINY 角色，否则 smol），或本地设备端模型。",
  "API format for Kimi Code provider (auto follows live model metadata)": "Kimi Code 提供商的 API 格式（auto 跟随实时模型元数据）",
  "Websocket policy for OpenAI Codex models (auto uses model defaults, on forces, off disables)": "OpenAI Codex 模型的 Websocket 策略（auto 使用模型默认值，on 强制，off 禁用）",
  "Prompt-cache retention forwarded to providers that support it (Anthropic, Bedrock, OpenRouter, OpenAI)": "转发给支持它的提供商的提示缓存保留（Anthropic、Bedrock、OpenRouter、OpenAI）",
  "Seconds to wait for the first model stream event; -1 uses provider/env defaults, 0 disables the watchdog": "等待第一个模型流事件的秒数；-1 使用提供商/环境默认值，0 禁用看门狗",
  "Seconds a model stream may stay silent between events; -1 uses provider/env defaults, 0 disables the watchdog": "模型流在事件间可保持静默的秒数；-1 使用提供商/环境默认值，0 禁用看门狗",
  "Default routing-variant suffix appended to OpenRouter model IDs (overridden when the selector already names a variant)": "附加到 OpenRouter model ID 的默认路由变体后缀（当选择器已命名变体时覆盖）",
  "Reader backend priority for the fetch/read URL tool": "fetch/read URL 工具的读取器后端优先级",
  "Spend saved Codex rate-limit resets automatically: restore an account blocked by an exhausted 5h or weekly window when a turn is stuck and no other account can take over, and salvage credits that are about to expire. unset asks before the first spend, yes spends without prompting, and no disables both checks.": "自动花费保存的 Codex 限速重置：当一轮卡住且无其他账户可接管时，恢复被耗尽的 5 小时或每周窗口阻止的账户，并挽救即将过期的额度。unset 在首次花费前询问，yes 不提示即花费，no 禁用两项检查。",
  "Only auto-redeem when the natural unblock — the latest reset among the exhausted 5h/weekly windows — is at least this many minutes away (don't spend a scarce credit to save a short wait). Raise it (e.g. 360) to ignore 5h-only blocks.": "仅当自然解除阻止——耗尽的 5 小时/每周窗口中最近的重置——至少还有这么多分钟时才自动赎回（不要花费稀缺额度来节省短等待）。提高它（如 360）可忽略仅 5 小时的阻止。",
  "Never auto-spend below this many saved resets (0 = the last credit may be spent automatically). Credits about to expire are exempt — a reserved credit that expires preserves nothing.": "永远不低于这么多已保存重置就自动花费（0 = 最后额度可能被自动花费）。即将过期的额度除外——过期的保留额度不保留任何东西。",
  "Spend a saved Codex reset automatically when it would otherwise expire within this many hours and either chat window (5h or weekly) has meaningful usage to restore (0 disables expiry salvage).": "当保存的 Codex 重置本会在这么多小时内过期，且任一聊天窗口（5 小时或每周）有可恢复的有意义用量时，自动花费（0 禁用过期挽救）。",
  "Cache system prompt + tool specs and keep an append-only message log so provider prefix caches (DeepSeek, Xiaomi/SGLang, Anthropic) hit at maximum rate. Auto enables for known prefix-cache providers.": "缓存系统提示 + 工具规范并保留仅追加消息日志，使提供商前缀缓存（DeepSeek、小米/SGLang、Anthropic）以最大速率命中。auto 对已知前缀缓存提供商启用。",
  "Enable the Exa web search provider": "启用 Exa 网络搜索提供商",
  "Minimum delay between Exa web search requests in milliseconds; set 0 to disable pacing": "Exa 网络搜索请求间的最小延迟（毫秒）；设为 0 禁用节流",
  "Base URL of a self-hosted SearXNG instance used for web search": "用于网络搜索的自托管 SearXNG 实例的基础 URL",
  "Positive finite active-work timeout for extension tool_call handlers; invalid values use 30000ms, and time awaiting OMP-owned dialogs does not count": "扩展 tool_call 处理程序的正有限活动工作超时；无效值使用 30000 毫秒，等待 OMP 拥有对话框的时间不计入",
  "Automated tool issue reporting (xd://report_issue). On by default; the first report asks for consent, and denying it disables reporting until re-enabled explicitly": "自动化工具问题报告（xd://report_issue）。默认开启；首次报告会询问同意，拒绝则禁用报告直到显式重新启用",
  "Full URL receiving Auto QA JSON reports (default https://qa.omp.sh/v1/grievances)": "接收 Auto QA JSON 报告的完整 URL（默认 https://qa.omp.sh/v1/grievances）",
};

/**
 * 针对 OMP 原生 schema 中未提供英文描述的 125 个配置项，逐个补齐详尽的中文说明。
 */
export const KEY_DESCRIPTIONS_ZH: Record<string, string> = {
  setupVersion: "OMP 配置架构版本号，用于引导向导和配置迁移检测。",
  "auth.broker.url": "身份认证代理 (Broker) 服务的 URL 地址，用于跨进程/跨设备同步认证凭据。",
  "auth.broker.token": "身份认证代理服务的访问授权令牌 (Token)。",
  shellPath: "终端会话所使用的默认 Shell 绝对路径（如 /bin/zsh 或 /bin/bash）。",
  extensions: "已启用的 OMP 扩展插件标识列表。",
  enabledModels: "允许会话调用的模型白名单列表（留空表示不作白名单限制）。",
  enabledProviders: "显式启用的模型提供商列表（留空表示全部启用）。",
  disabledProviders: "禁用的模型提供商列表，这些提供商将不会出现在模型切换列表中。",
  disabledExtensions: "禁用的扩展插件列表。",
  modelRoles: "各模型角色（如 default、advisor、smol 等）到具体模型标识符的映射字典。",
  modelTags: "用于分类和过滤模型的标签字典。",
  modelProviderOrder: "多提供商自动选取或回退时的优先顺序列表。",
  cycleOrder: "快捷键循环切换模型时的角色顺序列表（如 smol、default、slow）。",
  "statusLine.leftSegments": "状态行左侧显示的组件列表（如 model、git、tokens 等）。",
  "statusLine.rightSegments": "状态行右侧显示的组件列表（如 context、time、clock 等）。",
  "statusLine.segmentOptions": "状态行各字段组件的高级定制参数字典。",
  "images.urls.options": "图像服务 URL 发布配置参数选项。",
  "images.urls.credentials": "图像托管服务的访问凭据字典。",
  "tui.maxInlineImageColumns": "终端中内联渲染图像的最大列宽字符数。",
  "tui.maxInlineImageRows": "终端中内联渲染图像的最大行高行数。",
  "tui.maxInlineImages": "终端滚动历史缓冲中最多保留的内联图像数量。",
  "retry.enabled": "遇到网络或 API 错误时是否自动发起重试。",
  "retry.baseDelayMs": "首次 API 错误重试的基础退避延迟时间（毫秒）。",
  "stt.language": "语音转文字 (STT) 识别的主语言代码（如 zh 或 en）。",
  "compaction.reserveTokens": "上下文压缩时预留给模型后续输出的 Token 预算（设为空使用默认值）。",
  "compaction.keepRecentTokens": "上下文压缩时强制保留的最近轮次 Token 预算。",
  "compaction.autoContinue": "上下文压缩触发并完成后，是否自动恢复继续执行任务。",
  "compaction.remoteEndpoint": "执行远程摘要压缩的模型专用服务接口端点。",
  "compaction.v2RetainedMessageBudget": "V2 压缩算法保留最近历史消息的最大 Token 上限。",
  "branchSummary.reserveTokens": "离开分支生成分支摘要时预留的 Token 预算上限。",
  "memories.enabled": "是否启用持久化长期记忆库功能。",
  "memories.maxRolloutsPerStartup": "每次启动时单次最多回放和扫描的历史会话数量。",
  "memories.maxRolloutAgeDays": "纳入记忆提取的历史会话最大天数限制。",
  "memories.minRolloutIdleHours": "会话需闲置满多少小时后才会被纳入记忆提炼流程。",
  "memories.threadScanLimit": "单次记忆提取任务中扫描的历史消息上限条数。",
  "memories.maxRawMemoriesForGlobal": "全局记忆库中最多保留的原始记忆条数。",
  "memories.stage1Concurrency": "记忆提取阶段一（分析提炼）的最大并发任务数。",
  "memories.stage1LeaseSeconds": "阶段一记忆提取任务的分布式租约超时时间（秒）。",
  "memories.stage1RetryDelaySeconds": "阶段一失败后的重试等待间隔（秒）。",
  "memories.phase2LeaseSeconds": "阶段二记忆合并任务的分布式租约超时时间（秒）。",
  "memories.phase2RetryDelaySeconds": "阶段二合并失败后的重试等待间隔（秒）。",
  "memories.phase2HeartbeatSeconds": "阶段二后台任务的心跳保活间隔（秒）。",
  "memories.rolloutPayloadPercent": "回放有效载荷占总上下文预算的最大百分比比例。",
  "memories.phase1InputTokenLimit": "阶段一输入模型的最大 Token 限制。",
  "memories.fallbackTokenLimit": "记忆提取回退方案允许的最大 Token 预算。",
  "memories.summaryInjectionTokenLimit": "记忆摘要注入对话上下文时的最大 Token 上限。",
  "sharpshooter.intervalMinutes": "Sharpshooter 精准记忆定位的触发执行间隔（分钟）。",
  "sharpshooter.injectionTokenLimit": "Sharpshooter 注入上下文的最大 Token 预算限制。",
  "autolearn.minToolCalls": "触发经验自动学习与技能沉淀所需的最小工具调用轮次。",
  "mnemopi.retainEveryNTurns": "Mnemopi 记忆引擎每隔多少轮对话触发一次记忆持久化写入。",
  "mnemopi.recallLimit": "单次召回向上下文注入的最大 Mnemopi 记忆条数。",
  "mnemopi.recallContextTurns": "召回检索计算时参考的最近上下文轮数。",
  "mnemopi.recallMaxQueryChars": "召回向量检索查询文本的最大字符截断长度。",
  "mnemopi.injectionTokenLimit": "Mnemopi 记忆注入上下文的最大 Token 预算。",
  "mnemopi.debug": "是否开启 Mnemopi 本地记忆引擎的详细调试日志。",
  "hindsight.bankIdPrefix": "Hindsight 记忆库标识符自定义前缀。",
  "hindsight.bankMission": "Hindsight 记忆库核心业务目标与使命描述。",
  "hindsight.retainMission": "记忆沉淀时重点关注和保留的使命目标说明。",
  "hindsight.retainEveryNTurns": "Hindsight 记忆沉淀每隔多少轮对话自动执行一次。",
  "hindsight.retainOverlapTurns": "记忆提炼窗口滑动时的跨轮次重叠轮数。",
  "hindsight.retainContext": "记忆存储所属的上下文域标识符（默认 omp）。",
  "hindsight.recallBudget": "Hindsight 记忆召回推理计算的预算等级（low / mid / high）。",
  "hindsight.recallMaxTokens": "Hindsight 召回内容注入上下文的最大 Token 限制。",
  "hindsight.recallContextTurns": "召回分析所参考的历史对话轮数。",
  "hindsight.recallMaxQueryChars": "召回检索查询字符串的最大字符上限。",
  "hindsight.recallTypes": "召回的记忆类型列表（如 world、experience 等）。",
  "hindsight.debug": "是否开启 Hindsight 远程反思记忆服务的调试模式。",
  "hindsight.requestTimeoutMs": "Hindsight 网络请求超时时间（毫秒）。",
  "hindsight.reflectTimeoutMs": "Hindsight 反思提炼任务超时时间（毫秒）。",
  "hindsight.recallTimeoutMs": "Hindsight 召回检索操作超时时间（毫秒）。",
  "hindsight.retainTimeoutMs": "Hindsight 记忆写入持久化超时时间（毫秒）。",
  "hindsight.mentalModelRefreshIntervalMs": "心智模型 (Mental Model) 自动刷新间隔（毫秒）。",
  "hindsight.mentalModelMaxRenderChars": "心智模型注入上下文时的最大渲染字符数。",
  "bashInterceptor.patterns": "Bash 命令拦截规则列表，用于将高频终端操作重定向为原生安全工具（如将 cat 重定向为 read 工具）。",
  "shellMinimizer.settingsPath": "Shell 输出精简器规则配置文件的绝对路径。",
  "shellMinimizer.only": "仅对指定命令名称的输出执行精简过滤（留空表示不限制）。",
  "shellMinimizer.except": "排除指定命令名称，不进行输出精简过滤。",
  "shellMinimizer.maxCaptureBytes": "Shell 输出捕获与精简处理的最大字节上限。",
  "shellMinimizer.legacyFilters": "是否兼容并应用旧版本的 Shell 输出过滤规则。",
  "eval.autoBackground.thresholdMs": "代码求值执行超过该时间（毫秒）后自动转入后台异步运行。",
  "inspect_image.enabled": "是否启用专用图像检查与细节分析工具。",
  "async.maxJobs": "系统中允许同时运行的最大异步后台作业数量。",
  "bash.autoBackground.thresholdMs": "Bash 终端命令执行超过该时间（毫秒）后自动转为后台作业。",
  "task.disabledAgents": "禁用的子任务智能体类型名称列表。",
  "task.agentModelOverrides": "针对各子任务智能体单独指定的模型覆盖映射配置。",
  "task.agentPrewalk": "子任务智能体的预演执行策略与配置字典。",
  "task.agentAdvisor": "子任务智能体的第二模型顾问辅助配置字典。",
  "skills.enabled": "是否全局启用技能 (Skills) 扩展生态系统。",
  "skills.enableCodexUser": "是否加载用户目录下的 ~/.codex/skills 技能。",
  "skills.enableClaudeUser": "是否加载用户目录下的 ~/.claude/skills 技能。",
  "skills.enableClaudeProject": "是否加载项目根目录下的 .claude/skills 技能。",
  "skills.enablePiUser": "是否加载用户目录下的 ~/.omp/agent/skills 技能。",
  "skills.enablePiProject": "是否加载项目根目录下的 .omp/skills 技能。",
  "skills.enableAgentsUser": "是否加载通用智能体目录下的 ~/.agents/skills 技能。",
  "skills.enableAgentsProject": "是否加载项目目录下的 .agents/skills 技能。",
  "skills.customDirectories": "额外自定义技能扫描目录路径列表。",
  "skills.ignoredSkills": "显式禁用的技能名称列表。",
  "skills.includeSkills": "仅允许加载的技能白名单列表（留空表示全部允许）。",
  "searxng.token": "SearXNG 搜索引擎实例的 API 访问令牌。",
  "searxng.basicUsername": "SearXNG HTTP Basic 认证用户名。",
  "searxng.basicPassword": "SearXNG HTTP Basic 认证密码。",
  "searxng.categories": "SearXNG 默认搜索分类（如 general、science 等）。",
  "searxng.engines": "SearXNG 启用的搜索引擎列表（如 google、duckduckgo）。",
  "searxng.language": "SearXNG 搜索结果的首选语言代码（如 zh-CN）。",
  "searxng.safesearch": "SearXNG 安全搜索过滤级别（0 = 关闭，1 = 中度，2 = 严格）。",
  "commit.mapReduceEnabled": "生成大型代码提交说明时是否启用分阶段 Map-Reduce 总结算法。",
  "commit.mapReduceThreshold": "触发 Map-Reduce 分阶段总结的 diff 变更行数阈值。",
  "commit.mapBatchTokenBudget": "Map 分批提炼时单批次分配的 Token 预算。",
  "commit.cacheEnabled": "是否缓存提交说明分析计算结果以避免重复调用大模型。",
  "commit.cacheTtlDays": "Git 提交说明分析缓存的有效天数。",
  "commit.changelogMaxDiffChars": "生成变更日志 (Changelog) 时读取的最大 diff 字符数。",
  "dev.autoqaPush.token": "Auto QA 自动化质量诊断上报接口的 API Token。",
  "dev.autoqaConsent": "Auto QA 诊断日志收集与上传授权状态（granted = 已授权，denied = 已拒绝）。",
  "gc.blobs": "垃圾回收清理时是否清理未被引用的图片及二进制文件 Blobs。",
  "gc.archive": "垃圾回收清理时是否自动归档长期未活跃的历史会话。",
  "gc.wal": "垃圾回收时是否清理并截断 SQLite 数据库 WAL 预写日志文件。",
  "gc.coldArchiveAfterDays": "会话在最后修改多少天后自动移入冷归档存储。",
  "gc.retainNewestGlobal": "全局范围内始终保留的最少最新活跃会话数量。",
  "gc.retainNewestPerCwd": "每个工作区目录下始终保留的最少最新活跃会话数量。",
  "thinkingBudgets.minimal": "极低思考深度 (minimal) 对应的 Token 思考预算上限。",
  "thinkingBudgets.low": "低思考深度 (low) 对应的 Token 思考预算上限。",
  "thinkingBudgets.medium": "中等思考深度 (medium) 对应的 Token 思考预算上限。",
  "thinkingBudgets.high": "高思考深度 (high) 对应的 Token 思考预算上限。",
  "thinkingBudgets.xhigh": "极高思考深度 (xhigh) 对应的 Token 思考预算上限。",
  "thinkingBudgets.max": "最大思考深度 (max) 对应的 Token 思考预算上限。",
};

/**
 * 常见配置项中文友好标题映射表。
 */
export const KEY_TITLES_ZH: Record<string, string> = {
  // 通用与界面外观
  autoResume: "自动恢复最近会话",
  colorBlindMode: "色盲辅助高对比度模式",
  cycleOrder: "模型快捷切换轮换顺序",
  display: "显示设置",
  language: "界面语言",
  mode: "默认工作模式",
  showImages: "终端内嵌渲染图像",
  showSplash: "启动问候动画画面",
  smoothStreaming: "平滑流式输出呈现",
  shellPath: "默认 Shell 路径",
  setupVersion: "配置架构版本",
  symbolPreset: "图标符号预设方案",
  "theme.dark": "终端深色主题",
  "theme.light": "终端浅色主题",
  "composer.shape": "输入编辑器边框样式",
  "statusLine.preset": "状态行预设布局",
  "statusLine.separator": "状态行段间分隔符风格",
  "statusLine.contextLine": "上下文余量状态连接线",
  "statusLine.leftSegments": "状态行左侧展示字段",
  "statusLine.rightSegments": "状态行右侧展示字段",
  "statusLine.segmentOptions": "状态行字段参数配置",
  "tui.maxInlineImageColumns": "内联图像最大宽度",
  "tui.maxInlineImageRows": "内联图像最大高度",
  "tui.maxInlineImages": "内联图像历史保留数",
  "tui.resizeScrollback": "终端尺寸变动历史刷新",
  "tui.hyperlinks": "路径与 URL 原生超链接",
  "display.shimmer": "等待加载动效样式",
  "edit.mode": "代码编辑生效模式",

  // 模型与推理
  defaultThinkingLevel: "默认思考推理深度",
  compactThinkingLevel: "压缩总结思考深度",
  hideThinkingBlock: "在回复中折叠隐藏思考块",
  externalThinking: "独立草稿思考工具 (think)",
  textVerbosity: "文本回复详细程度",
  personality: "系统提示词人设风格",
  maxEffort: "最大思考努力程度",
  enabledModels: "允许调用的模型白名单",
  enabledProviders: "显式启用的模型提供商",
  disabledProviders: "禁用的模型提供商",
  modelRoles: "各模型角色对应模型",
  modelTags: "模型特征标签字典",
  modelProviderOrder: "模型提供商优先级列表",
  "thinkingBudgets.minimal": "思考预算 - 极低 (minimal)",
  "thinkingBudgets.low": "思考预算 - 低 (low)",
  "thinkingBudgets.medium": "思考预算 - 中 (medium)",
  "thinkingBudgets.high": "思考预算 - 高 (high)",
  "thinkingBudgets.xhigh": "思考预算 - 极高 (xhigh)",
  "thinkingBudgets.max": "思考预算 - 最大 (max)",
  "images.urls.options": "图像服务 URL 发布配置",
  "images.urls.credentials": "图像托管服务访问凭据",
  "inspect_image.enabled": "启用图像细节分析工具",
  "stt.language": "语音识别语言",

  // 工具与安全
  approvalMode: "全局工具审批策略",
  "tools.approvalMode": "全局工具审批策略",
  "tools.approval": "特定工具审批覆盖规则",
  "tools.format": "工具结果呈现格式",
  "git.enabled": "启用 Git 状态与分支监控",
  "bash.autoBackground.thresholdMs": "Bash 自动转入后台运行阈值",
  "bashInterceptor.patterns": "Bash 命令拦截重定向规则",
  "shellMinimizer.settingsPath": "Shell 输出精简配置文件",
  "shellMinimizer.only": "Shell 输出精简包含白名单",
  "shellMinimizer.except": "Shell 输出精简排除黑名单",
  "shellMinimizer.maxCaptureBytes": "Shell 捕获最大字节限制",
  "eval.autoBackground.thresholdMs": "代码求值自动转后台阈值",
  "async.maxJobs": "最大异步后台任务数",

  // 智能体与流程
  "advisor.enabled": "启用副模型顾问 (Advisor)",
  "advisor.syncBacklog": "顾问落后暂停等待轮数",
  "advisor.immuneTurns": "顾问提醒非中断轮数",
  "prewalk.enabled": "强模型规划后自动交接 (Prewalk)",
  "retry.enabled": "启用 API 请求自动重试",
  "retry.maxAttempts": "API 请求最大重试次数",
  "retry.baseDelayMs": "重试基础退避延迟",
  "retry.modelFallback": "重试耗尽时切换备用模型",
  "compaction.strategy": "长会话上下文压缩策略",
  "compaction.reserveTokens": "压缩时预留 Token 预算",
  "compaction.keepRecentTokens": "压缩时保留最近 Token 数",
  "compaction.autoContinue": "压缩完成后自动继续执行",
  "compaction.remoteEndpoint": "远程压缩服务接口端点",
  "compaction.v2RetainedMessageBudget": "V2 压缩消息保留上限",
  "branchSummary.reserveTokens": "分支摘要预留 Token 上限",
  "task.disabledAgents": "禁用的子任务代理类型",
  "task.agentModelOverrides": "子任务代理模型覆盖映射",

  // 记忆与上下文
  "memory.backend": "长期记忆存储后端",
  "memories.enabled": "启用持久化长期记忆库",
  "memories.maxRolloutsPerStartup": "启动扫描最大历史会话数",
  "memories.maxRolloutAgeDays": "记忆扫描最大历史天数",
  "memories.minRolloutIdleHours": "纳入记忆提取的闲置时间",
  "memories.threadScanLimit": "单次记忆提取消息上限",
  "memories.maxRawMemoriesForGlobal": "全局库最大原始记忆数",
  "memories.stage1Concurrency": "记忆提取阶段一并发数",
  "memories.stage1LeaseSeconds": "记忆提取阶段一租约时长",
  "memories.stage1RetryDelaySeconds": "记忆提取阶段一重试延迟",
  "memories.phase2LeaseSeconds": "记忆合并阶段二租约时长",
  "memories.phase2RetryDelaySeconds": "记忆合并阶段二重试延迟",
  "memories.phase2HeartbeatSeconds": "记忆合并阶段二心跳间隔",
  "memories.rolloutPayloadPercent": "回放有效载荷百分比上限",
  "memories.phase1InputTokenLimit": "阶段一输入 Token 限制",
  "memories.fallbackTokenLimit": "记忆提取回退 Token 限制",
  "memories.summaryInjectionTokenLimit": "记忆摘要注入 Token 上限",
  "sharpshooter.intervalMinutes": "Sharpshooter 记忆定位间隔",
  "sharpshooter.injectionTokenLimit": "Sharpshooter 注入 Token 上限",
  "autolearn.minToolCalls": "经验自动学习触发最小工具数",
  "mnemopi.retainEveryNTurns": "Mnemopi 记忆写入轮次间隔",
  "mnemopi.recallLimit": "Mnemopi 单次召回最大条数目",
  "mnemopi.recallContextTurns": "Mnemopi 召回参考上下文轮数",
  "mnemopi.recallMaxQueryChars": "Mnemopi 召回查询最大字符数",
  "mnemopi.injectionTokenLimit": "Mnemopi 记忆注入 Token 预算",
  "mnemopi.debug": "Mnemopi 本地记忆调试模式",
  "hindsight.bankIdPrefix": "Hindsight 记忆库标识前缀",
  "hindsight.bankMission": "Hindsight 核心业务使命描述",
  "hindsight.retainMission": "Hindsight 沉淀重点关注使命",
  "hindsight.retainEveryNTurns": "Hindsight 记忆沉淀轮次间隔",
  "hindsight.retainOverlapTurns": "Hindsight 记忆提取重叠轮数",
  "hindsight.retainContext": "Hindsight 记忆上下文域标识",
  "hindsight.recallBudget": "Hindsight 召回推理计算预算",
  "hindsight.recallMaxTokens": "Hindsight 召回注入 Token 上限",
  "hindsight.recallContextTurns": "Hindsight 召回参考上下文轮数",
  "hindsight.recallMaxQueryChars": "Hindsight 召回查询最大字符数",
  "hindsight.recallTypes": "Hindsight 召回记忆类型列表",
  "hindsight.debug": "Hindsight 远程反思调试模式",
  "hindsight.requestTimeoutMs": "Hindsight 网络请求超时时间",
  "hindsight.reflectTimeoutMs": "Hindsight 反思提炼超时时间",
  "hindsight.recallTimeoutMs": "Hindsight 召回检索超时时间",
  "hindsight.retainTimeoutMs": "Hindsight 记忆写入持久化超时",
  "hindsight.mentalModelRefreshIntervalMs": "心智模型自动刷新间隔",
  "hindsight.mentalModelMaxRenderChars": "心智模型最大渲染字符数",

  // 扩展与集成
  extensions: "已启用的扩展插件",
  disabledExtensions: "已禁用的扩展插件",
  "auth.broker.url": "认证代理 Broker 服务地址",
  "auth.broker.token": "认证代理 Broker 访问令牌",
  "skills.enabled": "全局启用技能系统",
  "skills.enableCodexUser": "加载 Codex 用户级技能",
  "skills.enableClaudeUser": "加载 Claude 用户级技能",
  "skills.enableClaudeProject": "加载 Claude 项目级技能",
  "skills.enablePiUser": "加载 OMP 用户级技能",
  "skills.enablePiProject": "加载 OMP 项目级技能",
  "skills.enableAgentsUser": "加载 Agents 通用用户技能",
  "skills.enableAgentsProject": "加载 Agents 通用项目技能",
  "skills.customDirectories": "自定义技能扫描路径列表",
  "skills.ignoredSkills": "禁用忽略的技能列表",
  "skills.includeSkills": "显式允许的技能白名单",
  "searxng.token": "SearXNG 访问令牌",
  "searxng.basicUsername": "SearXNG HTTP Basic 用户名",
  "searxng.basicPassword": "SearXNG HTTP Basic 密码",
  "searxng.categories": "SearXNG 默认搜索类别",
  "searxng.engines": "SearXNG 搜索引擎列表",
  "searxng.language": "SearXNG 搜索返回语言",
  "searxng.safesearch": "SearXNG 安全搜索等级",
  "commit.mapReduceEnabled": "大提交分阶段总结 (Map-Reduce)",
  "commit.mapReduceThreshold": "提交说明总结触发行数阈值",
  "commit.mapBatchTokenBudget": "提交说明分批总结 Token 预算",
  "commit.cacheEnabled": "提交说明分析缓存",
  "commit.cacheTtlDays": "提交说明分析缓存保留天数",
  "commit.changelogMaxDiffChars": "变更日志读取最大 diff 字符数",

  // 开发者与系统选项
  "dev.autoqaConsent": "Auto QA 质量诊断上报授权",
  "dev.autoqaPush.token": "Auto QA 上报接口 Token",
  "power.sleepPrevention": "阻止系统休眠策略",
  "update.channel": "OMP 更新发布渠道",
  "gc.blobs": "清理孤立图片与大文件 Blobs",
  "gc.archive": "自动归档闲置历史会话",
  "gc.wal": "清理 SQLite WAL 预写日志",
  "gc.coldArchiveAfterDays": "会话转入冷归档闲置天数",
  "gc.retainNewestGlobal": "全局保留最少活跃会话数",
  "gc.retainNewestPerCwd": "各工作区保留最少活跃会话数",
};

/**
 * 子分类中文名称映射表。
 */
export const SUBGROUP_LABELS_ZH: Record<string, string> = {
  general: "基础常规",
  basic: "基础常规",
  theme: "主题外观",
  statusLine: "状态行",
  composer: "输入编辑器",
  display: "界面显示",
  tui: "终端界面",
  workspace: "工作区",
  spelling: "拼写检查",
  paste: "粘贴处理",
  startup: "启动流程",
  update: "更新检测",
  completion: "补全与通知",
  recap: "进度回顾",
  collab: "协同共享",
  share: "会话分享",
  branchSummary: "分支摘要",
  edit: "代码编辑",
  images: "图像处理",
  loopGuard: "循环守护",
  toolCallLoopGuard: "工具调用守护",
  tier: "服务层级配额",
  loop: "循环迭代",
  stt: "语音识别 (STT)",
  speechgen: "语音生成",
  generate_image: "图像生成",
  inspect_image: "图像分析",
  tts: "文本转语音 (TTS)",
  speech: "语音交互",
  thinkingBudgets: "思考预算",
  bash: "Bash 终端",
  git: "Git 版本控制",
  terminal: "终端集成",
  ask: "交互询问",
  read: "文件读取",
  lsp: "语言服务 (LSP)",
  bashInterceptor: "命令拦截器",
  shellMinimizer: "输出精简器",
  python: "Python 执行",
  approval: "工具审批",
  approvalMode: "审批模式",
  todo: "待办清单",
  glob: "文件匹配",
  grep: "文本搜索",
  astGrep: "AST 语法搜索",
  astEdit: "AST 语法编辑",
  computer: "电脑控制",
  checkpoint: "检查点",
  fetch: "网络请求",
  web_search: "网络搜索",
  security: "安全检查",
  browser: "浏览器工具",
  intentTracing: "意图追踪",
  isolation: "环境隔离",
  worktree: "工作区树 (Worktree)",
  commands: "自定义命令",
  commit: "代码提交",
  advisor: "副模型顾问",
  prewalk: "预演交接",
  retry: "自动重试",
  compaction: "上下文压缩",
  async: "异步任务",
  plan: "执行计划",
  goal: "目标分解",
  task: "子任务代理",
  tasks: "任务管理",
  memories: "长期记忆库",
  backend: "存储后端",
  mnemopi: "Mnemopi 记忆",
  hindsight: "Hindsight 反思记忆",
  sharpshooter: "精准定位记忆",
  autolearn: "自动经验学习",
  contextPromotion: "上下文提升",
  snapcompact: "快照压缩",
  ttsr: "TTSR 检索",
  auth: "认证鉴权",
  providers: "模型提供商",
  marketplace: "插件市场",
  vault: "密钥保险箱",
  github: "GitHub 集成",
  irc: "IRC 协议",
  mcp: "MCP 扩展协议",
  skills: "技能系统 (Skills)",
  secrets: "机密信息脱敏",
  provider: "提供商配置",
  exa: "Exa 搜索引擎",
  searxng: "SearXNG 搜索引擎",
  extensionHandlers: "扩展处理器",
  eval: "代码求值执行",
  debug: "调试诊断",
  dev: "开发者选项",
  error: "错误处理",
  power: "电源与休眠",
  magicKeywords: "魔法指令",
  launch: "启动参数",
  title: "标题生成",
  live: "实时通讯",
  features: "实验特性",
  codexResets: "Codex 配额重置",
  gc: "垃圾回收",
};

/**
 * 常用枚举项中文含义对照表。
 */
export const ENUM_LABELS_ZH: Record<string, Record<string, string>> = {
  "tools.approvalMode": {
    "always-ask": "总是询问确认 (always-ask)",
    write: "仅修改写入时询问 (write)",
    yolo: "自动批准执行 (yolo)",
  },
  approvalMode: {
    "always-ask": "总是询问确认 (always-ask)",
    write: "仅修改写入时询问 (write)",
    yolo: "自动批准执行 (yolo)",
  },
  "memory.backend": {
    off: "关闭记忆 (off)",
    local: "本地 SQLite 数据库 (local)",
    mnemopi: "Mnemopi 知识库 (mnemopi)",
    hindsight: "Hindsight 远程反思服务 (hindsight)",
    sharpshooter: "Sharpshooter 精准定位 (sharpshooter)",
  },
  "compaction.strategy": {
    snapcompact: "快照压缩归档 (snapcompact)",
    handoff: "生成任务交接文档 (handoff)",
    "context-full": "保留完整上下文 (context-full)",
    shake: "抖动裁剪丢弃历史 (shake)",
    off: "关闭自动压缩 (off)",
  },
  defaultThinkingLevel: {
    auto: "自动按模型确定 (auto)",
    minimal: "极低预算 (minimal)",
    low: "低预算 (low)",
    medium: "中等预算 (medium)",
    high: "高预算 (high)",
    xhigh: "极高预算 (xhigh)",
    max: "最大预算 (max)",
  },
  compactThinkingLevel: {
    auto: "自动 (auto)",
    minimal: "极低预算 (minimal)",
    low: "低预算 (low)",
    medium: "中等预算 (medium)",
    high: "高预算 (high)",
    xhigh: "极高预算 (xhigh)",
    max: "最大预算 (max)",
  },
  textVerbosity: {
    low: "简明扼要 (low)",
    medium: "适度均衡 (medium)",
    high: "详细全面 (high)",
  },
  "power.sleepPrevention": {
    none: "不阻止系统休眠 (none)",
    idle: "空闲会话时阻止休眠 (idle)",
    active: "仅在运行活跃时阻止 (active)",
  },
  "update.channel": {
    stable: "稳定正式版 (stable)",
    beta: "公开测试版 (beta)",
    nightly: "每夜尝鲜版 (nightly)",
  },
  symbolPreset: {
    unicode: "标准 Unicode 字符集 (unicode)",
    nerd: "Nerd Font 开发者字形 (nerd)",
    ascii: "纯 ASCII 兼容符号 (ascii)",
  },
  "edit.mode": {
    hashline: "哈希行锚点模式 (hashline)",
    patch: "统一补丁模式 (patch)",
    whole: "整文件覆写模式 (whole)",
  },
  "dev.autoqaConsent": {
    granted: "已同意授权 (granted)",
    denied: "已拒绝授权 (denied)",
  },
  "hindsight.recallBudget": {
    low: "低计算预算 (low)",
    mid: "中等预算 (mid)",
    high: "高计算预算 (high)",
  },
  "hindsight.retainMode": {
    off: "关闭沉淀 (off)",
    auto: "自动沉淀 (auto)",
    manual: "仅手动沉淀 (manual)",
  },
  "stt.submitTrigger": {
    never: "从不自动提交 (never)",
    release: "松开输入后提交 (release)",
    sentence: "完整句子结束时提交 (sentence)",
    keyword: "说出提交口令时提交 (keyword)",
  },
  "shellMinimizer.sourceOutlineLevel": {
    off: "关闭大纲提取 (off)",
    minimal: "提取核心摘要 (minimal)",
    full: "提取完整结构大纲 (full)",
  },
  "python.kernelMode": {
    auto: "自动选择内核 (auto)",
    persistent: "持久化常驻内核 (persistent)",
    isolated: "每次单独隔离启动 (isolated)",
  },
  "isolation.backend": {
    auto: "自动检测最佳隔离后端 (auto)",
    cow: "写时复制 (CoW 文件系统)",
    projfs: "ProjFS 虚拟文件系统",
    worktree: "Git Worktree 隔离工作树",
  },
  "speech.mode": {
    off: "关闭语音 (off)",
    streaming: "实时流式语音交互 (streaming)",
    batch: "分批整段语音生成 (batch)",
  },
};

/**
 * 翻译配置项友好中文标题。
 */
export function translateKeyTitle(locale: string | null | undefined, key: string): string | undefined {
  if (!locale?.startsWith("zh")) return undefined;
  if (KEY_TITLES_ZH[key]) return KEY_TITLES_ZH[key];
  return undefined;
}

/**
 * 翻译配置项说明描述：
 * 优先匹配原生描述映射，若原生描述为空或未命中则回退到配置项键级别的中文说明字典。
 */
export function translateDescription(locale: string | null | undefined, en: string | undefined, key?: string): string | undefined {
  if (!locale?.startsWith("zh")) return en;
  if (en && MAP[en]) return MAP[en];
  if (key && KEY_DESCRIPTIONS_ZH[key]) return KEY_DESCRIPTIONS_ZH[key];
  return en;
}

/**
 * 翻译左侧侧边栏子分类名称。
 */
export function translateSubgroup(locale: string | null | undefined, sub: string): string {
  if (!locale?.startsWith("zh")) return sub.replace(/[-_]/g, " ");
  if (SUBGROUP_LABELS_ZH[sub]) return SUBGROUP_LABELS_ZH[sub];
  const parts = sub.split(/(?=[A-Z])|[-_]/).filter(Boolean);
  const translatedParts = parts.map((p) => SUBGROUP_LABELS_ZH[p.toLowerCase()] ?? p);
  if (translatedParts.some((p) => p !== parts[0])) {
    return translatedParts.join("");
  }
  return sub.replace(/[-_]/g, " ");
}

/**
 * 翻译枚举项的下拉选项标签。
 */
export function translateEnumOption(locale: string | null | undefined, key: string, option: string): string {
  if (!locale?.startsWith("zh")) return option;
  const keyMap = ENUM_LABELS_ZH[key];
  if (keyMap && keyMap[option]) return keyMap[option];
  const lastKey = key.split(".").pop();
  if (lastKey && ENUM_LABELS_ZH[lastKey]?.[option]) return ENUM_LABELS_ZH[lastKey][option];
  return option;
}

/**
 * 格式化配置项类型徽章。
 */
export function formatSettingType(locale: string | null | undefined, type: string): string {
  if (!locale?.startsWith("zh")) return type;
  switch (type) {
    case "boolean": return "布尔";
    case "number": return "数字";
    case "string": return "文本";
    case "enum": return "枚举";
    case "array": return "列表";
    case "record": return "键值对";
    case "object": return "对象";
    default: return type;
  }
}

